//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alias",
    "mailto",
    "residence",
    "currentincome",
    "declaration",
    "dependent",
    "employer",
    "fhavaborrower",
    "governmentmonitoring",
    "presenthousingexpense",
    "summary",
    "vaborrower",
    "contactpoint"
})
@XmlRootElement(name = "BORROWER")
public class BORROWER {

    @XmlAttribute(name = "BorrowerID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String borrowerID;
    @XmlAttribute(name = "JointAssetBorrowerID")
    @XmlIDREF
    protected java.lang.Object jointAssetBorrowerID;
    @XmlAttribute(name = "_UnparsedName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String unparsedName;
    @XmlAttribute(name = "_FirstName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String firstName;
    @XmlAttribute(name = "_MiddleName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String middleName;
    @XmlAttribute(name = "_LastName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lastName;
    @XmlAttribute(name = "_NameSuffix")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nameSuffix;
    @XmlAttribute(name = "_AgeAtApplicationYears")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ageAtApplicationYears;
    @XmlAttribute(name = "_BirthDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String birthDate;
    @XmlAttribute(name = "_ApplicationSignedDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String applicationSignedDate;
    @XmlAttribute(name = "_HomeTelephoneNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String homeTelephoneNumber;
    @XmlAttribute(name = "_PrintPositionType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String printPositionType;
    @XmlAttribute(name = "_SSN", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ssn;
    @XmlAttribute(name = "DependentCount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dependentCount;
    @XmlAttribute(name = "JointAssetLiabilityReportingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jointAssetLiabilityReportingType;
    @XmlAttribute(name = "MaritalStatusType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maritalStatusType;
    @XmlAttribute(name = "SchoolingYears")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String schoolingYears;
    @XmlAttribute(name = "CreditReportIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creditReportIdentifier;
    @XmlElement(name = "_ALIAS")
    protected List<ALIAS> alias;
    @XmlElement(name = "_MAIL_TO")
    protected MAILTO mailto;
    @XmlElement(name = "_RESIDENCE")
    protected List<RESIDENCE> residence;
    @XmlElement(name = "CURRENT_INCOME")
    protected List<CURRENTINCOME> currentincome;
    @XmlElement(name = "DECLARATION")
    protected DECLARATION declaration;
    @XmlElement(name = "DEPENDENT")
    protected List<DEPENDENT> dependent;
    @XmlElement(name = "EMPLOYER")
    protected List<EMPLOYER> employer;
    @XmlElement(name = "FHA_VA_BORROWER")
    protected FHAVABORROWER fhavaborrower;
    @XmlElement(name = "GOVERNMENT_MONITORING")
    protected GOVERNMENTMONITORING governmentmonitoring;
    @XmlElement(name = "PRESENT_HOUSING_EXPENSE")
    protected List<PRESENTHOUSINGEXPENSE> presenthousingexpense;
    @XmlElement(name = "SUMMARY")
    protected List<SUMMARY> summary;
    @XmlElement(name = "VA_BORROWER")
    protected VABORROWER vaborrower;
    @XmlElement(name = "CONTACT_POINT")
    protected List<CONTACTPOINT> contactpoint;

    /**
     * Gets the value of the borrowerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrowerID() {
        return borrowerID;
    }

    /**
     * Sets the value of the borrowerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrowerID(String value) {
        this.borrowerID = value;
    }

    /**
     * Gets the value of the jointAssetBorrowerID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Object }
     *     
     */
    public java.lang.Object getJointAssetBorrowerID() {
        return jointAssetBorrowerID;
    }

    /**
     * Sets the value of the jointAssetBorrowerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Object }
     *     
     */
    public void setJointAssetBorrowerID(java.lang.Object value) {
        this.jointAssetBorrowerID = value;
    }

    /**
     * Gets the value of the unparsedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnparsedName() {
        return unparsedName;
    }

    /**
     * Sets the value of the unparsedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnparsedName(String value) {
        this.unparsedName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the nameSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSuffix(String value) {
        this.nameSuffix = value;
    }

    /**
     * Gets the value of the ageAtApplicationYears property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeAtApplicationYears() {
        return ageAtApplicationYears;
    }

    /**
     * Sets the value of the ageAtApplicationYears property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeAtApplicationYears(String value) {
        this.ageAtApplicationYears = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the applicationSignedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationSignedDate() {
        return applicationSignedDate;
    }

    /**
     * Sets the value of the applicationSignedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationSignedDate(String value) {
        this.applicationSignedDate = value;
    }

    /**
     * Gets the value of the homeTelephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeTelephoneNumber() {
        return homeTelephoneNumber;
    }

    /**
     * Sets the value of the homeTelephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeTelephoneNumber(String value) {
        this.homeTelephoneNumber = value;
    }

    /**
     * Gets the value of the printPositionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintPositionType() {
        return printPositionType;
    }

    /**
     * Sets the value of the printPositionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintPositionType(String value) {
        this.printPositionType = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSN() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSN(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the dependentCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDependentCount() {
        return dependentCount;
    }

    /**
     * Sets the value of the dependentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDependentCount(String value) {
        this.dependentCount = value;
    }

    /**
     * Gets the value of the jointAssetLiabilityReportingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJointAssetLiabilityReportingType() {
        return jointAssetLiabilityReportingType;
    }

    /**
     * Sets the value of the jointAssetLiabilityReportingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJointAssetLiabilityReportingType(String value) {
        this.jointAssetLiabilityReportingType = value;
    }

    /**
     * Gets the value of the maritalStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatusType() {
        return maritalStatusType;
    }

    /**
     * Sets the value of the maritalStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatusType(String value) {
        this.maritalStatusType = value;
    }

    /**
     * Gets the value of the schoolingYears property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolingYears() {
        return schoolingYears;
    }

    /**
     * Sets the value of the schoolingYears property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolingYears(String value) {
        this.schoolingYears = value;
    }

    /**
     * Gets the value of the creditReportIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditReportIdentifier() {
        return creditReportIdentifier;
    }

    /**
     * Sets the value of the creditReportIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditReportIdentifier(String value) {
        this.creditReportIdentifier = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getALIAS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ALIAS }
     * 
     * 
     */
    public List<ALIAS> getALIAS() {
        if (alias == null) {
            alias = new ArrayList<ALIAS>();
        }
        return this.alias;
    }

    /**
     * Gets the value of the mailto property.
     * 
     * @return
     *     possible object is
     *     {@link MAILTO }
     *     
     */
    public MAILTO getMAILTO() {
        return mailto;
    }

    /**
     * Sets the value of the mailto property.
     * 
     * @param value
     *     allowed object is
     *     {@link MAILTO }
     *     
     */
    public void setMAILTO(MAILTO value) {
        this.mailto = value;
    }

    /**
     * Gets the value of the residence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the residence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRESIDENCE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RESIDENCE }
     * 
     * 
     */
    public List<RESIDENCE> getRESIDENCE() {
        if (residence == null) {
            residence = new ArrayList<RESIDENCE>();
        }
        return this.residence;
    }

    /**
     * Gets the value of the currentincome property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the currentincome property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCURRENTINCOME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CURRENTINCOME }
     * 
     * 
     */
    public List<CURRENTINCOME> getCURRENTINCOME() {
        if (currentincome == null) {
            currentincome = new ArrayList<CURRENTINCOME>();
        }
        return this.currentincome;
    }

    /**
     * Gets the value of the declaration property.
     * 
     * @return
     *     possible object is
     *     {@link DECLARATION }
     *     
     */
    public DECLARATION getDECLARATION() {
        return declaration;
    }

    /**
     * Sets the value of the declaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DECLARATION }
     *     
     */
    public void setDECLARATION(DECLARATION value) {
        this.declaration = value;
    }

    /**
     * Gets the value of the dependent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDEPENDENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEPENDENT }
     * 
     * 
     */
    public List<DEPENDENT> getDEPENDENT() {
        if (dependent == null) {
            dependent = new ArrayList<DEPENDENT>();
        }
        return this.dependent;
    }

    /**
     * Gets the value of the employer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEMPLOYER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EMPLOYER }
     * 
     * 
     */
    public List<EMPLOYER> getEMPLOYER() {
        if (employer == null) {
            employer = new ArrayList<EMPLOYER>();
        }
        return this.employer;
    }

    /**
     * Gets the value of the fhavaborrower property.
     * 
     * @return
     *     possible object is
     *     {@link FHAVABORROWER }
     *     
     */
    public FHAVABORROWER getFHAVABORROWER() {
        return fhavaborrower;
    }

    /**
     * Sets the value of the fhavaborrower property.
     * 
     * @param value
     *     allowed object is
     *     {@link FHAVABORROWER }
     *     
     */
    public void setFHAVABORROWER(FHAVABORROWER value) {
        this.fhavaborrower = value;
    }

    /**
     * Gets the value of the governmentmonitoring property.
     * 
     * @return
     *     possible object is
     *     {@link GOVERNMENTMONITORING }
     *     
     */
    public GOVERNMENTMONITORING getGOVERNMENTMONITORING() {
        return governmentmonitoring;
    }

    /**
     * Sets the value of the governmentmonitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link GOVERNMENTMONITORING }
     *     
     */
    public void setGOVERNMENTMONITORING(GOVERNMENTMONITORING value) {
        this.governmentmonitoring = value;
    }

    /**
     * Gets the value of the presenthousingexpense property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presenthousingexpense property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPRESENTHOUSINGEXPENSE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PRESENTHOUSINGEXPENSE }
     * 
     * 
     */
    public List<PRESENTHOUSINGEXPENSE> getPRESENTHOUSINGEXPENSE() {
        if (presenthousingexpense == null) {
            presenthousingexpense = new ArrayList<PRESENTHOUSINGEXPENSE>();
        }
        return this.presenthousingexpense;
    }

    /**
     * Gets the value of the summary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the summary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSUMMARY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SUMMARY }
     * 
     * 
     */
    public List<SUMMARY> getSUMMARY() {
        if (summary == null) {
            summary = new ArrayList<SUMMARY>();
        }
        return this.summary;
    }

    /**
     * Gets the value of the vaborrower property.
     * 
     * @return
     *     possible object is
     *     {@link VABORROWER }
     *     
     */
    public VABORROWER getVABORROWER() {
        return vaborrower;
    }

    /**
     * Sets the value of the vaborrower property.
     * 
     * @param value
     *     allowed object is
     *     {@link VABORROWER }
     *     
     */
    public void setVABORROWER(VABORROWER value) {
        this.vaborrower = value;
    }

    /**
     * Gets the value of the contactpoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactpoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONTACTPOINT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONTACTPOINT }
     * 
     * 
     */
    public List<CONTACTPOINT> getCONTACTPOINT() {
        if (contactpoint == null) {
            contactpoint = new ArrayList<CONTACTPOINT>();
        }
        return this.contactpoint;
    }

}
