//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creditcomment",
    "creditrepository",
    "verification"
})
@XmlRootElement(name = "CREDIT_PUBLIC_RECORD")
public class CREDITPUBLICRECORD {

    @XmlAttribute(name = "CreditPublicRecordID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String creditPublicRecordID;
    @XmlAttribute(name = "BorrowerID")
    @XmlIDREF
    protected List<java.lang.Object> borrowerID;
    @XmlAttribute(name = "CreditFileID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creditFileID;
    @XmlAttribute(name = "CreditTradeReferenceID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creditTradeReferenceID;
    @XmlAttribute(name = "_AccountOwnershipType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String accountOwnershipType;
    @XmlAttribute(name = "_AttorneyName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String attorneyName;
    @XmlAttribute(name = "_BankruptcyAdjustmentPercent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bankruptcyAdjustmentPercent;
    @XmlAttribute(name = "_BankruptcyAssetsAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bankruptcyAssetsAmount;
    @XmlAttribute(name = "_BankruptcyExemptAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bankruptcyExemptAmount;
    @XmlAttribute(name = "_BankruptcyLiabilitiesAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bankruptcyLiabilitiesAmount;
    @XmlAttribute(name = "_BankruptcyRepaymentPercent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bankruptcyRepaymentPercent;
    @XmlAttribute(name = "_BankruptcyType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bankruptcyType;
    @XmlAttribute(name = "_ConsumerDisputeIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String consumerDisputeIndicator;
    @XmlAttribute(name = "_CourtName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String courtName;
    @XmlAttribute(name = "_DefendantName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defendantName;
    @XmlAttribute(name = "_DerogatoryDataIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String derogatoryDataIndicator;
    @XmlAttribute(name = "_DispositionDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dispositionDate;
    @XmlAttribute(name = "_DispositionType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dispositionType;
    @XmlAttribute(name = "_DispositionTypeOtherDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dispositionTypeOtherDescription;
    @XmlAttribute(name = "_DocketIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String docketIdentifier;
    @XmlAttribute(name = "_FiledDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String filedDate;
    @XmlAttribute(name = "_LegalObligationAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String legalObligationAmount;
    @XmlAttribute(name = "_ManualUpdateIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String manualUpdateIndicator;
    @XmlAttribute(name = "_PaidDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String paidDate;
    @XmlAttribute(name = "_PaymentFrequencyType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String paymentFrequencyType;
    @XmlAttribute(name = "_PlaintiffName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String plaintiffName;
    @XmlAttribute(name = "_ReportedDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String reportedDate;
    @XmlAttribute(name = "_SettledDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String settledDate;
    @XmlAttribute(name = "_Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "_TypeOtherDescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String typeOtherDescription;
    @XmlElement(name = "CREDIT_COMMENT")
    protected List<CREDITCOMMENT> creditcomment;
    @XmlElement(name = "CREDIT_REPOSITORY")
    protected List<CREDITREPOSITORY> creditrepository;
    @XmlElement(name = "VERIFICATION")
    protected VERIFICATION verification;

    /**
     * Gets the value of the creditPublicRecordID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditPublicRecordID() {
        return creditPublicRecordID;
    }

    /**
     * Sets the value of the creditPublicRecordID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditPublicRecordID(String value) {
        this.creditPublicRecordID = value;
    }

    /**
     * Gets the value of the borrowerID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the borrowerID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBorrowerID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.Object }
     * 
     * 
     */
    public List<java.lang.Object> getBorrowerID() {
        if (borrowerID == null) {
            borrowerID = new ArrayList<java.lang.Object>();
        }
        return this.borrowerID;
    }

    /**
     * Gets the value of the creditFileID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditFileID() {
        return creditFileID;
    }

    /**
     * Sets the value of the creditFileID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditFileID(String value) {
        this.creditFileID = value;
    }

    /**
     * Gets the value of the creditTradeReferenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditTradeReferenceID() {
        return creditTradeReferenceID;
    }

    /**
     * Sets the value of the creditTradeReferenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditTradeReferenceID(String value) {
        this.creditTradeReferenceID = value;
    }

    /**
     * Gets the value of the accountOwnershipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountOwnershipType() {
        return accountOwnershipType;
    }

    /**
     * Sets the value of the accountOwnershipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountOwnershipType(String value) {
        this.accountOwnershipType = value;
    }

    /**
     * Gets the value of the attorneyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttorneyName() {
        return attorneyName;
    }

    /**
     * Sets the value of the attorneyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttorneyName(String value) {
        this.attorneyName = value;
    }

    /**
     * Gets the value of the bankruptcyAdjustmentPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankruptcyAdjustmentPercent() {
        return bankruptcyAdjustmentPercent;
    }

    /**
     * Sets the value of the bankruptcyAdjustmentPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankruptcyAdjustmentPercent(String value) {
        this.bankruptcyAdjustmentPercent = value;
    }

    /**
     * Gets the value of the bankruptcyAssetsAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankruptcyAssetsAmount() {
        return bankruptcyAssetsAmount;
    }

    /**
     * Sets the value of the bankruptcyAssetsAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankruptcyAssetsAmount(String value) {
        this.bankruptcyAssetsAmount = value;
    }

    /**
     * Gets the value of the bankruptcyExemptAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankruptcyExemptAmount() {
        return bankruptcyExemptAmount;
    }

    /**
     * Sets the value of the bankruptcyExemptAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankruptcyExemptAmount(String value) {
        this.bankruptcyExemptAmount = value;
    }

    /**
     * Gets the value of the bankruptcyLiabilitiesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankruptcyLiabilitiesAmount() {
        return bankruptcyLiabilitiesAmount;
    }

    /**
     * Sets the value of the bankruptcyLiabilitiesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankruptcyLiabilitiesAmount(String value) {
        this.bankruptcyLiabilitiesAmount = value;
    }

    /**
     * Gets the value of the bankruptcyRepaymentPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankruptcyRepaymentPercent() {
        return bankruptcyRepaymentPercent;
    }

    /**
     * Sets the value of the bankruptcyRepaymentPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankruptcyRepaymentPercent(String value) {
        this.bankruptcyRepaymentPercent = value;
    }

    /**
     * Gets the value of the bankruptcyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankruptcyType() {
        return bankruptcyType;
    }

    /**
     * Sets the value of the bankruptcyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankruptcyType(String value) {
        this.bankruptcyType = value;
    }

    /**
     * Gets the value of the consumerDisputeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerDisputeIndicator() {
        return consumerDisputeIndicator;
    }

    /**
     * Sets the value of the consumerDisputeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerDisputeIndicator(String value) {
        this.consumerDisputeIndicator = value;
    }

    /**
     * Gets the value of the courtName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourtName() {
        return courtName;
    }

    /**
     * Sets the value of the courtName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourtName(String value) {
        this.courtName = value;
    }

    /**
     * Gets the value of the defendantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefendantName() {
        return defendantName;
    }

    /**
     * Sets the value of the defendantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefendantName(String value) {
        this.defendantName = value;
    }

    /**
     * Gets the value of the derogatoryDataIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDerogatoryDataIndicator() {
        return derogatoryDataIndicator;
    }

    /**
     * Sets the value of the derogatoryDataIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDerogatoryDataIndicator(String value) {
        this.derogatoryDataIndicator = value;
    }

    /**
     * Gets the value of the dispositionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispositionDate() {
        return dispositionDate;
    }

    /**
     * Sets the value of the dispositionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispositionDate(String value) {
        this.dispositionDate = value;
    }

    /**
     * Gets the value of the dispositionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispositionType() {
        return dispositionType;
    }

    /**
     * Sets the value of the dispositionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispositionType(String value) {
        this.dispositionType = value;
    }

    /**
     * Gets the value of the dispositionTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispositionTypeOtherDescription() {
        return dispositionTypeOtherDescription;
    }

    /**
     * Sets the value of the dispositionTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispositionTypeOtherDescription(String value) {
        this.dispositionTypeOtherDescription = value;
    }

    /**
     * Gets the value of the docketIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocketIdentifier() {
        return docketIdentifier;
    }

    /**
     * Sets the value of the docketIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocketIdentifier(String value) {
        this.docketIdentifier = value;
    }

    /**
     * Gets the value of the filedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiledDate() {
        return filedDate;
    }

    /**
     * Sets the value of the filedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiledDate(String value) {
        this.filedDate = value;
    }

    /**
     * Gets the value of the legalObligationAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalObligationAmount() {
        return legalObligationAmount;
    }

    /**
     * Sets the value of the legalObligationAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalObligationAmount(String value) {
        this.legalObligationAmount = value;
    }

    /**
     * Gets the value of the manualUpdateIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManualUpdateIndicator() {
        return manualUpdateIndicator;
    }

    /**
     * Sets the value of the manualUpdateIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManualUpdateIndicator(String value) {
        this.manualUpdateIndicator = value;
    }

    /**
     * Gets the value of the paidDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaidDate() {
        return paidDate;
    }

    /**
     * Sets the value of the paidDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaidDate(String value) {
        this.paidDate = value;
    }

    /**
     * Gets the value of the paymentFrequencyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentFrequencyType() {
        return paymentFrequencyType;
    }

    /**
     * Sets the value of the paymentFrequencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentFrequencyType(String value) {
        this.paymentFrequencyType = value;
    }

    /**
     * Gets the value of the plaintiffName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaintiffName() {
        return plaintiffName;
    }

    /**
     * Sets the value of the plaintiffName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaintiffName(String value) {
        this.plaintiffName = value;
    }

    /**
     * Gets the value of the reportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportedDate() {
        return reportedDate;
    }

    /**
     * Sets the value of the reportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedDate(String value) {
        this.reportedDate = value;
    }

    /**
     * Gets the value of the settledDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettledDate() {
        return settledDate;
    }

    /**
     * Sets the value of the settledDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettledDate(String value) {
        this.settledDate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the typeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOtherDescription() {
        return typeOtherDescription;
    }

    /**
     * Sets the value of the typeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOtherDescription(String value) {
        this.typeOtherDescription = value;
    }

    /**
     * Gets the value of the creditcomment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditcomment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCREDITCOMMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CREDITCOMMENT }
     * 
     * 
     */
    public List<CREDITCOMMENT> getCREDITCOMMENT() {
        if (creditcomment == null) {
            creditcomment = new ArrayList<CREDITCOMMENT>();
        }
        return this.creditcomment;
    }

    /**
     * Gets the value of the creditrepository property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditrepository property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCREDITREPOSITORY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CREDITREPOSITORY }
     * 
     * 
     */
    public List<CREDITREPOSITORY> getCREDITREPOSITORY() {
        if (creditrepository == null) {
            creditrepository = new ArrayList<CREDITREPOSITORY>();
        }
        return this.creditrepository;
    }

    /**
     * Gets the value of the verification property.
     * 
     * @return
     *     possible object is
     *     {@link VERIFICATION }
     *     
     */
    public VERIFICATION getVERIFICATION() {
        return verification;
    }

    /**
     * Sets the value of the verification property.
     * 
     * @param value
     *     allowed object is
     *     {@link VERIFICATION }
     *     
     */
    public void setVERIFICATION(VERIFICATION value) {
        this.verification = value;
    }

}
