//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "FHA_LOAN")
public class FHALOAN {

    @XmlAttribute(name = "BorrowerFinancedFHADiscountPointsAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String borrowerFinancedFHADiscountPointsAmount;
    @XmlAttribute(name = "FHAAlimonyLiabilityTreatmentType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fhaAlimonyLiabilityTreatmentType;
    @XmlAttribute(name = "FHACoverageRenewalRatePercent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fhaCoverageRenewalRatePercent;
    @XmlAttribute(name = "FHA_MIPremiumRefundAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fhamiPremiumRefundAmount;
    @XmlAttribute(name = "FHAUpfrontMIPremiumPercent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String fhaUpfrontMIPremiumPercent;
    @XmlAttribute(name = "_LenderIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lenderIdentifier;
    @XmlAttribute(name = "_SponsorIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sponsorIdentifier;
    @XmlAttribute(name = "SectionOfActType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sectionOfActType;

    /**
     * Gets the value of the borrowerFinancedFHADiscountPointsAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrowerFinancedFHADiscountPointsAmount() {
        return borrowerFinancedFHADiscountPointsAmount;
    }

    /**
     * Sets the value of the borrowerFinancedFHADiscountPointsAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrowerFinancedFHADiscountPointsAmount(String value) {
        this.borrowerFinancedFHADiscountPointsAmount = value;
    }

    /**
     * Gets the value of the fhaAlimonyLiabilityTreatmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFHAAlimonyLiabilityTreatmentType() {
        return fhaAlimonyLiabilityTreatmentType;
    }

    /**
     * Sets the value of the fhaAlimonyLiabilityTreatmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFHAAlimonyLiabilityTreatmentType(String value) {
        this.fhaAlimonyLiabilityTreatmentType = value;
    }

    /**
     * Gets the value of the fhaCoverageRenewalRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFHACoverageRenewalRatePercent() {
        return fhaCoverageRenewalRatePercent;
    }

    /**
     * Sets the value of the fhaCoverageRenewalRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFHACoverageRenewalRatePercent(String value) {
        this.fhaCoverageRenewalRatePercent = value;
    }

    /**
     * Gets the value of the fhamiPremiumRefundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFHAMIPremiumRefundAmount() {
        return fhamiPremiumRefundAmount;
    }

    /**
     * Sets the value of the fhamiPremiumRefundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFHAMIPremiumRefundAmount(String value) {
        this.fhamiPremiumRefundAmount = value;
    }

    /**
     * Gets the value of the fhaUpfrontMIPremiumPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFHAUpfrontMIPremiumPercent() {
        return fhaUpfrontMIPremiumPercent;
    }

    /**
     * Sets the value of the fhaUpfrontMIPremiumPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFHAUpfrontMIPremiumPercent(String value) {
        this.fhaUpfrontMIPremiumPercent = value;
    }

    /**
     * Gets the value of the lenderIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLenderIdentifier() {
        return lenderIdentifier;
    }

    /**
     * Sets the value of the lenderIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLenderIdentifier(String value) {
        this.lenderIdentifier = value;
    }

    /**
     * Gets the value of the sponsorIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSponsorIdentifier() {
        return sponsorIdentifier;
    }

    /**
     * Sets the value of the sponsorIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSponsorIdentifier(String value) {
        this.sponsorIdentifier = value;
    }

    /**
     * Gets the value of the sectionOfActType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectionOfActType() {
        return sectionOfActType;
    }

    /**
     * Sets the value of the sectionOfActType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectionOfActType(String value) {
        this.sectionOfActType = value;
    }

}
