//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PAYMENT_ADJUSTMENT")
public class PAYMENTADJUSTMENT {

    @XmlAttribute(name = "FirstPaymentAdjustmentMonths")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String firstPaymentAdjustmentMonths;
    @XmlAttribute(name = "_Amount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String amount;
    @XmlAttribute(name = "_CalculationType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String calculationType;
    @XmlAttribute(name = "_DurationMonths")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String durationMonths;
    @XmlAttribute(name = "_Percent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String percent;
    @XmlAttribute(name = "_PeriodicCapAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String periodicCapAmount;
    @XmlAttribute(name = "_PeriodicCapPercent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String periodicCapPercent;
    @XmlAttribute(name = "_PeriodNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String periodNumber;
    @XmlAttribute(name = "SubsequentPaymentAdjustmentMonths")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subsequentPaymentAdjustmentMonths;

    /**
     * Gets the value of the firstPaymentAdjustmentMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstPaymentAdjustmentMonths() {
        return firstPaymentAdjustmentMonths;
    }

    /**
     * Sets the value of the firstPaymentAdjustmentMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstPaymentAdjustmentMonths(String value) {
        this.firstPaymentAdjustmentMonths = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the calculationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculationType() {
        return calculationType;
    }

    /**
     * Sets the value of the calculationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculationType(String value) {
        this.calculationType = value;
    }

    /**
     * Gets the value of the durationMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationMonths() {
        return durationMonths;
    }

    /**
     * Sets the value of the durationMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationMonths(String value) {
        this.durationMonths = value;
    }

    /**
     * Gets the value of the percent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercent() {
        return percent;
    }

    /**
     * Sets the value of the percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercent(String value) {
        this.percent = value;
    }

    /**
     * Gets the value of the periodicCapAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicCapAmount() {
        return periodicCapAmount;
    }

    /**
     * Sets the value of the periodicCapAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicCapAmount(String value) {
        this.periodicCapAmount = value;
    }

    /**
     * Gets the value of the periodicCapPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicCapPercent() {
        return periodicCapPercent;
    }

    /**
     * Sets the value of the periodicCapPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicCapPercent(String value) {
        this.periodicCapPercent = value;
    }

    /**
     * Gets the value of the periodNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodNumber() {
        return periodNumber;
    }

    /**
     * Sets the value of the periodNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodNumber(String value) {
        this.periodNumber = value;
    }

    /**
     * Gets the value of the subsequentPaymentAdjustmentMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsequentPaymentAdjustmentMonths() {
        return subsequentPaymentAdjustmentMonths;
    }

    /**
     * Sets the value of the subsequentPaymentAdjustmentMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsequentPaymentAdjustmentMonths(String value) {
        this.subsequentPaymentAdjustmentMonths = value;
    }

}
