//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "legaldescription",
    "parsedstreetaddress",
    "valuation"
})
@XmlRootElement(name = "PROPERTY")
public class PROPERTY {

    @XmlAttribute(name = "_StreetAddress")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String streetAddress;
    @XmlAttribute(name = "_StreetAddress2")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String streetAddress2;
    @XmlAttribute(name = "_City")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String city;
    @XmlAttribute(name = "_State")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String state;
    @XmlAttribute(name = "_County")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String county;
    @XmlAttribute(name = "_PostalCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String postalCode;
    @XmlAttribute(name = "BuildingStatusType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String buildingStatusType;
    @XmlAttribute(name = "_FinancedNumberOfUnits")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String financedNumberOfUnits;
    @XmlAttribute(name = "_StructureBuiltYear")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String structureBuiltYear;
    @XmlAttribute(name = "_AcquiredDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String acquiredDate;
    @XmlAttribute(name = "PlannedUnitDevelopmentIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String plannedUnitDevelopmentIndicator;
    @XmlAttribute(name = "_AcreageNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String acreageNumber;
    @XmlElement(name = "_LEGAL_DESCRIPTION")
    protected List<LEGALDESCRIPTION> legaldescription;
    @XmlElement(name = "PARSED_STREET_ADDRESS")
    protected PARSEDSTREETADDRESS parsedstreetaddress;
    @XmlElement(name = "_VALUATION")
    protected List<VALUATION> valuation;

    /**
     * Gets the value of the streetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * Sets the value of the streetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddress(String value) {
        this.streetAddress = value;
    }

    /**
     * Gets the value of the streetAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress2() {
        return streetAddress2;
    }

    /**
     * Sets the value of the streetAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddress2(String value) {
        this.streetAddress2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the buildingStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingStatusType() {
        return buildingStatusType;
    }

    /**
     * Sets the value of the buildingStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingStatusType(String value) {
        this.buildingStatusType = value;
    }

    /**
     * Gets the value of the financedNumberOfUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancedNumberOfUnits() {
        return financedNumberOfUnits;
    }

    /**
     * Sets the value of the financedNumberOfUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancedNumberOfUnits(String value) {
        this.financedNumberOfUnits = value;
    }

    /**
     * Gets the value of the structureBuiltYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStructureBuiltYear() {
        return structureBuiltYear;
    }

    /**
     * Sets the value of the structureBuiltYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStructureBuiltYear(String value) {
        this.structureBuiltYear = value;
    }

    /**
     * Gets the value of the acquiredDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquiredDate() {
        return acquiredDate;
    }

    /**
     * Sets the value of the acquiredDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquiredDate(String value) {
        this.acquiredDate = value;
    }

    /**
     * Gets the value of the plannedUnitDevelopmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedUnitDevelopmentIndicator() {
        return plannedUnitDevelopmentIndicator;
    }

    /**
     * Sets the value of the plannedUnitDevelopmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedUnitDevelopmentIndicator(String value) {
        this.plannedUnitDevelopmentIndicator = value;
    }

    /**
     * Gets the value of the acreageNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcreageNumber() {
        return acreageNumber;
    }

    /**
     * Sets the value of the acreageNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcreageNumber(String value) {
        this.acreageNumber = value;
    }

    /**
     * Gets the value of the legaldescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legaldescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLEGALDESCRIPTION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LEGALDESCRIPTION }
     * 
     * 
     */
    public List<LEGALDESCRIPTION> getLEGALDESCRIPTION() {
        if (legaldescription == null) {
            legaldescription = new ArrayList<LEGALDESCRIPTION>();
        }
        return this.legaldescription;
    }

    /**
     * Gets the value of the parsedstreetaddress property.
     * 
     * @return
     *     possible object is
     *     {@link PARSEDSTREETADDRESS }
     *     
     */
    public PARSEDSTREETADDRESS getPARSEDSTREETADDRESS() {
        return parsedstreetaddress;
    }

    /**
     * Sets the value of the parsedstreetaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARSEDSTREETADDRESS }
     *     
     */
    public void setPARSEDSTREETADDRESS(PARSEDSTREETADDRESS value) {
        this.parsedstreetaddress = value;
    }

    /**
     * Gets the value of the valuation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVALUATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VALUATION }
     * 
     * 
     */
    public List<VALUATION> getVALUATION() {
        if (valuation == null) {
            valuation = new ArrayList<VALUATION>();
        }
        return this.valuation;
    }

}
