//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "REO_PROPERTY")
public class REOPROPERTY {

    @XmlAttribute(name = "REO_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String reoid;
    @XmlAttribute(name = "BorrowerID")
    @XmlIDREF
    protected List<java.lang.Object> borrowerID;
    @XmlAttribute(name = "LiabilityID")
    @XmlIDREF
    protected List<java.lang.Object> liabilityID;
    @XmlAttribute(name = "_StreetAddress")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String streetAddress;
    @XmlAttribute(name = "_StreetAddress2")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String streetAddress2;
    @XmlAttribute(name = "_City")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String city;
    @XmlAttribute(name = "_State")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String state;
    @XmlAttribute(name = "_PostalCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String postalCode;
    @XmlAttribute(name = "_CurrentResidenceIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String currentResidenceIndicator;
    @XmlAttribute(name = "_DispositionStatusType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dispositionStatusType;
    @XmlAttribute(name = "_GSEPropertyType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String gsePropertyType;
    @XmlAttribute(name = "_LienInstallmentAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lienInstallmentAmount;
    @XmlAttribute(name = "_LienUPBAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lienUPBAmount;
    @XmlAttribute(name = "_MaintenanceExpenseAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maintenanceExpenseAmount;
    @XmlAttribute(name = "_MarketValueAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String marketValueAmount;
    @XmlAttribute(name = "_RentalIncomeGrossAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rentalIncomeGrossAmount;
    @XmlAttribute(name = "_RentalIncomeNetAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rentalIncomeNetAmount;
    @XmlAttribute(name = "_SubjectIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String subjectIndicator;

    /**
     * Gets the value of the reoid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREOID() {
        return reoid;
    }

    /**
     * Sets the value of the reoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREOID(String value) {
        this.reoid = value;
    }

    /**
     * Gets the value of the borrowerID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the borrowerID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBorrowerID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.Object }
     * 
     * 
     */
    public List<java.lang.Object> getBorrowerID() {
        if (borrowerID == null) {
            borrowerID = new ArrayList<java.lang.Object>();
        }
        return this.borrowerID;
    }

    /**
     * Gets the value of the liabilityID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the liabilityID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLiabilityID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.Object }
     * 
     * 
     */
    public List<java.lang.Object> getLiabilityID() {
        if (liabilityID == null) {
            liabilityID = new ArrayList<java.lang.Object>();
        }
        return this.liabilityID;
    }

    /**
     * Gets the value of the streetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * Sets the value of the streetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddress(String value) {
        this.streetAddress = value;
    }

    /**
     * Gets the value of the streetAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress2() {
        return streetAddress2;
    }

    /**
     * Sets the value of the streetAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddress2(String value) {
        this.streetAddress2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the currentResidenceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentResidenceIndicator() {
        return currentResidenceIndicator;
    }

    /**
     * Sets the value of the currentResidenceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentResidenceIndicator(String value) {
        this.currentResidenceIndicator = value;
    }

    /**
     * Gets the value of the dispositionStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispositionStatusType() {
        return dispositionStatusType;
    }

    /**
     * Sets the value of the dispositionStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispositionStatusType(String value) {
        this.dispositionStatusType = value;
    }

    /**
     * Gets the value of the gsePropertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGSEPropertyType() {
        return gsePropertyType;
    }

    /**
     * Sets the value of the gsePropertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGSEPropertyType(String value) {
        this.gsePropertyType = value;
    }

    /**
     * Gets the value of the lienInstallmentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLienInstallmentAmount() {
        return lienInstallmentAmount;
    }

    /**
     * Sets the value of the lienInstallmentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLienInstallmentAmount(String value) {
        this.lienInstallmentAmount = value;
    }

    /**
     * Gets the value of the lienUPBAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLienUPBAmount() {
        return lienUPBAmount;
    }

    /**
     * Sets the value of the lienUPBAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLienUPBAmount(String value) {
        this.lienUPBAmount = value;
    }

    /**
     * Gets the value of the maintenanceExpenseAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaintenanceExpenseAmount() {
        return maintenanceExpenseAmount;
    }

    /**
     * Sets the value of the maintenanceExpenseAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaintenanceExpenseAmount(String value) {
        this.maintenanceExpenseAmount = value;
    }

    /**
     * Gets the value of the marketValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketValueAmount() {
        return marketValueAmount;
    }

    /**
     * Sets the value of the marketValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketValueAmount(String value) {
        this.marketValueAmount = value;
    }

    /**
     * Gets the value of the rentalIncomeGrossAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRentalIncomeGrossAmount() {
        return rentalIncomeGrossAmount;
    }

    /**
     * Sets the value of the rentalIncomeGrossAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRentalIncomeGrossAmount(String value) {
        this.rentalIncomeGrossAmount = value;
    }

    /**
     * Gets the value of the rentalIncomeNetAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRentalIncomeNetAmount() {
        return rentalIncomeNetAmount;
    }

    /**
     * Sets the value of the rentalIncomeNetAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRentalIncomeNetAmount(String value) {
        this.rentalIncomeNetAmount = value;
    }

    /**
     * Gets the value of the subjectIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectIndicator() {
        return subjectIndicator;
    }

    /**
     * Sets the value of the subjectIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectIndicator(String value) {
        this.subjectIndicator = value;
    }

}
