//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "key",
    "requestdata"
})
@XmlRootElement(name = "REQUEST")
public class REQUEST {

    @XmlAttribute(name = "RequestDatetime")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requestDatetime;
    @XmlAttribute(name = "InternalAccountIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String internalAccountIdentifier;
    @XmlAttribute(name = "LoginAccountIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String loginAccountIdentifier;
    @XmlAttribute(name = "LoginAccountPassword")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String loginAccountPassword;
    @XmlAttribute(name = "RequestingPartyBranchIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String requestingPartyBranchIdentifier;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElement(name = "KEY")
    protected List<KEY> key;
    @XmlElement(name = "REQUEST_DATA")
    protected List<REQUESTDATA> requestdata;

    /**
     * Gets the value of the requestDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDatetime() {
        return requestDatetime;
    }

    /**
     * Sets the value of the requestDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDatetime(String value) {
        this.requestDatetime = value;
    }

    /**
     * Gets the value of the internalAccountIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalAccountIdentifier() {
        return internalAccountIdentifier;
    }

    /**
     * Sets the value of the internalAccountIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalAccountIdentifier(String value) {
        this.internalAccountIdentifier = value;
    }

    /**
     * Gets the value of the loginAccountIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginAccountIdentifier() {
        return loginAccountIdentifier;
    }

    /**
     * Sets the value of the loginAccountIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginAccountIdentifier(String value) {
        this.loginAccountIdentifier = value;
    }

    /**
     * Gets the value of the loginAccountPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginAccountPassword() {
        return loginAccountPassword;
    }

    /**
     * Sets the value of the loginAccountPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginAccountPassword(String value) {
        this.loginAccountPassword = value;
    }

    /**
     * Gets the value of the requestingPartyBranchIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestingPartyBranchIdentifier() {
        return requestingPartyBranchIdentifier;
    }

    /**
     * Sets the value of the requestingPartyBranchIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestingPartyBranchIdentifier(String value) {
        this.requestingPartyBranchIdentifier = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the key property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKEY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KEY }
     * 
     * 
     */
    public List<KEY> getKEY() {
        if (key == null) {
            key = new ArrayList<KEY>();
        }
        return this.key;
    }

    /**
     * Gets the value of the requestdata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestdata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREQUESTDATA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REQUESTDATA }
     * 
     * 
     */
    public List<REQUESTDATA> getREQUESTDATA() {
        if (requestdata == null) {
            requestdata = new ArrayList<REQUESTDATA>();
        }
        return this.requestdata;
    }

}
