//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parsedstreetaddress",
    "landlord"
})
@XmlRootElement(name = "_RESIDENCE")
public class RESIDENCE {

    @XmlAttribute(name = "_StreetAddress")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String streetAddress;
    @XmlAttribute(name = "_City")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String city;
    @XmlAttribute(name = "_State")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String state;
    @XmlAttribute(name = "_PostalCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String postalCode;
    @XmlAttribute(name = "_Country")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String country;
    @XmlAttribute(name = "BorrowerResidencyBasisType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String borrowerResidencyBasisType;
    @XmlAttribute(name = "BorrowerResidencyDurationMonths")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String borrowerResidencyDurationMonths;
    @XmlAttribute(name = "BorrowerResidencyDurationYears")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String borrowerResidencyDurationYears;
    @XmlAttribute(name = "BorrowerResidencyType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String borrowerResidencyType;
    @XmlAttribute(name = "MonthlyRentAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String monthlyRentAmount;
    @XmlAttribute(name = "MonthlyRentCurrentRatingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String monthlyRentCurrentRatingType;
    @XmlElement(name = "PARSED_STREET_ADDRESS")
    protected PARSEDSTREETADDRESS parsedstreetaddress;
    @XmlElement(name = "LANDLORD")
    protected LANDLORD landlord;

    /**
     * Gets the value of the streetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * Sets the value of the streetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddress(String value) {
        this.streetAddress = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the borrowerResidencyBasisType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrowerResidencyBasisType() {
        return borrowerResidencyBasisType;
    }

    /**
     * Sets the value of the borrowerResidencyBasisType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrowerResidencyBasisType(String value) {
        this.borrowerResidencyBasisType = value;
    }

    /**
     * Gets the value of the borrowerResidencyDurationMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrowerResidencyDurationMonths() {
        return borrowerResidencyDurationMonths;
    }

    /**
     * Sets the value of the borrowerResidencyDurationMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrowerResidencyDurationMonths(String value) {
        this.borrowerResidencyDurationMonths = value;
    }

    /**
     * Gets the value of the borrowerResidencyDurationYears property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrowerResidencyDurationYears() {
        return borrowerResidencyDurationYears;
    }

    /**
     * Sets the value of the borrowerResidencyDurationYears property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrowerResidencyDurationYears(String value) {
        this.borrowerResidencyDurationYears = value;
    }

    /**
     * Gets the value of the borrowerResidencyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorrowerResidencyType() {
        return borrowerResidencyType;
    }

    /**
     * Sets the value of the borrowerResidencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorrowerResidencyType(String value) {
        this.borrowerResidencyType = value;
    }

    /**
     * Gets the value of the monthlyRentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthlyRentAmount() {
        return monthlyRentAmount;
    }

    /**
     * Sets the value of the monthlyRentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthlyRentAmount(String value) {
        this.monthlyRentAmount = value;
    }

    /**
     * Gets the value of the monthlyRentCurrentRatingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthlyRentCurrentRatingType() {
        return monthlyRentCurrentRatingType;
    }

    /**
     * Sets the value of the monthlyRentCurrentRatingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthlyRentCurrentRatingType(String value) {
        this.monthlyRentCurrentRatingType = value;
    }

    /**
     * Gets the value of the parsedstreetaddress property.
     * 
     * @return
     *     possible object is
     *     {@link PARSEDSTREETADDRESS }
     *     
     */
    public PARSEDSTREETADDRESS getPARSEDSTREETADDRESS() {
        return parsedstreetaddress;
    }

    /**
     * Sets the value of the parsedstreetaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARSEDSTREETADDRESS }
     *     
     */
    public void setPARSEDSTREETADDRESS(PARSEDSTREETADDRESS value) {
        this.parsedstreetaddress = value;
    }

    /**
     * Gets the value of the landlord property.
     * 
     * @return
     *     possible object is
     *     {@link LANDLORD }
     *     
     */
    public LANDLORD getLANDLORD() {
        return landlord;
    }

    /**
     * Sets the value of the landlord property.
     * 
     * @param value
     *     allowed object is
     *     {@link LANDLORD }
     *     
     */
    public void setLANDLORD(LANDLORD value) {
        this.landlord = value;
    }

}
