//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 01:17:24 AM CAT 
//


package qubed.creditservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TRANSMITTAL_DATA")
public class TRANSMITTALDATA {

    @XmlAttribute(name = "ArmsLengthIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String armsLengthIndicator;
    @XmlAttribute(name = "BelowMarketSubordinateFinancingIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String belowMarketSubordinateFinancingIndicator;
    @XmlAttribute(name = "BuydownRatePercent")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String buydownRatePercent;
    @XmlAttribute(name = "CaseStateType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String caseStateType;
    @XmlAttribute(name = "CreditReportAuthorizationIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String creditReportAuthorizationIndicator;
    @XmlAttribute(name = "CurrentFirstMortgageHolderType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String currentFirstMortgageHolderType;
    @XmlAttribute(name = "LenderBranchIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lenderBranchIdentifier;
    @XmlAttribute(name = "LenderRegistrationIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lenderRegistrationIdentifier;
    @XmlAttribute(name = "PropertyAppraisedValueAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String propertyAppraisedValueAmount;
    @XmlAttribute(name = "PropertyEstimatedValueAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String propertyEstimatedValueAmount;
    @XmlAttribute(name = "InvestorLoanIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String investorLoanIdentifier;
    @XmlAttribute(name = "InvestorInstitutionIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String investorInstitutionIdentifier;
    @XmlAttribute(name = "CommitmentReferenceIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String commitmentReferenceIdentifier;
    @XmlAttribute(name = "ConcurrentOriginationIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String concurrentOriginationIndicator;
    @XmlAttribute(name = "ConcurrentOriginationLenderIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String concurrentOriginationLenderIndicator;
    @XmlAttribute(name = "RateLockPeriodDays")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rateLockPeriodDays;
    @XmlAttribute(name = "RateLockType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rateLockType;
    @XmlAttribute(name = "RateLockRequestedExtensionDays")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rateLockRequestedExtensionDays;

    /**
     * Gets the value of the armsLengthIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArmsLengthIndicator() {
        return armsLengthIndicator;
    }

    /**
     * Sets the value of the armsLengthIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArmsLengthIndicator(String value) {
        this.armsLengthIndicator = value;
    }

    /**
     * Gets the value of the belowMarketSubordinateFinancingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelowMarketSubordinateFinancingIndicator() {
        return belowMarketSubordinateFinancingIndicator;
    }

    /**
     * Sets the value of the belowMarketSubordinateFinancingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelowMarketSubordinateFinancingIndicator(String value) {
        this.belowMarketSubordinateFinancingIndicator = value;
    }

    /**
     * Gets the value of the buydownRatePercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuydownRatePercent() {
        return buydownRatePercent;
    }

    /**
     * Sets the value of the buydownRatePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuydownRatePercent(String value) {
        this.buydownRatePercent = value;
    }

    /**
     * Gets the value of the caseStateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseStateType() {
        return caseStateType;
    }

    /**
     * Sets the value of the caseStateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseStateType(String value) {
        this.caseStateType = value;
    }

    /**
     * Gets the value of the creditReportAuthorizationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditReportAuthorizationIndicator() {
        return creditReportAuthorizationIndicator;
    }

    /**
     * Sets the value of the creditReportAuthorizationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditReportAuthorizationIndicator(String value) {
        this.creditReportAuthorizationIndicator = value;
    }

    /**
     * Gets the value of the currentFirstMortgageHolderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentFirstMortgageHolderType() {
        return currentFirstMortgageHolderType;
    }

    /**
     * Sets the value of the currentFirstMortgageHolderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentFirstMortgageHolderType(String value) {
        this.currentFirstMortgageHolderType = value;
    }

    /**
     * Gets the value of the lenderBranchIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLenderBranchIdentifier() {
        return lenderBranchIdentifier;
    }

    /**
     * Sets the value of the lenderBranchIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLenderBranchIdentifier(String value) {
        this.lenderBranchIdentifier = value;
    }

    /**
     * Gets the value of the lenderRegistrationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLenderRegistrationIdentifier() {
        return lenderRegistrationIdentifier;
    }

    /**
     * Sets the value of the lenderRegistrationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLenderRegistrationIdentifier(String value) {
        this.lenderRegistrationIdentifier = value;
    }

    /**
     * Gets the value of the propertyAppraisedValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyAppraisedValueAmount() {
        return propertyAppraisedValueAmount;
    }

    /**
     * Sets the value of the propertyAppraisedValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyAppraisedValueAmount(String value) {
        this.propertyAppraisedValueAmount = value;
    }

    /**
     * Gets the value of the propertyEstimatedValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyEstimatedValueAmount() {
        return propertyEstimatedValueAmount;
    }

    /**
     * Sets the value of the propertyEstimatedValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyEstimatedValueAmount(String value) {
        this.propertyEstimatedValueAmount = value;
    }

    /**
     * Gets the value of the investorLoanIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestorLoanIdentifier() {
        return investorLoanIdentifier;
    }

    /**
     * Sets the value of the investorLoanIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestorLoanIdentifier(String value) {
        this.investorLoanIdentifier = value;
    }

    /**
     * Gets the value of the investorInstitutionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestorInstitutionIdentifier() {
        return investorInstitutionIdentifier;
    }

    /**
     * Sets the value of the investorInstitutionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestorInstitutionIdentifier(String value) {
        this.investorInstitutionIdentifier = value;
    }

    /**
     * Gets the value of the commitmentReferenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommitmentReferenceIdentifier() {
        return commitmentReferenceIdentifier;
    }

    /**
     * Sets the value of the commitmentReferenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitmentReferenceIdentifier(String value) {
        this.commitmentReferenceIdentifier = value;
    }

    /**
     * Gets the value of the concurrentOriginationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcurrentOriginationIndicator() {
        return concurrentOriginationIndicator;
    }

    /**
     * Sets the value of the concurrentOriginationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcurrentOriginationIndicator(String value) {
        this.concurrentOriginationIndicator = value;
    }

    /**
     * Gets the value of the concurrentOriginationLenderIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcurrentOriginationLenderIndicator() {
        return concurrentOriginationLenderIndicator;
    }

    /**
     * Sets the value of the concurrentOriginationLenderIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcurrentOriginationLenderIndicator(String value) {
        this.concurrentOriginationLenderIndicator = value;
    }

    /**
     * Gets the value of the rateLockPeriodDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateLockPeriodDays() {
        return rateLockPeriodDays;
    }

    /**
     * Sets the value of the rateLockPeriodDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateLockPeriodDays(String value) {
        this.rateLockPeriodDays = value;
    }

    /**
     * Gets the value of the rateLockType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateLockType() {
        return rateLockType;
    }

    /**
     * Sets the value of the rateLockType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateLockType(String value) {
        this.rateLockType = value;
    }

    /**
     * Gets the value of the rateLockRequestedExtensionDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateLockRequestedExtensionDays() {
        return rateLockRequestedExtensionDays;
    }

    /**
     * Sets the value of the rateLockRequestedExtensionDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateLockRequestedExtensionDays(String value) {
        this.rateLockRequestedExtensionDays = value;
    }

}
