//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DOCUMENT_MANAGEMENT_REQUEST complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCUMENT_MANAGEMENT_REQUEST">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.mismo.org/residential/2009/schemas}PROPERTIES" minOccurs="0"/>
 *         &lt;element name="DOCUMENT_MANAGEMENT_REQUEST_DETAIL" type="{http://globalgateway.corelogic.com/order/2015}DOCUMENT_MANAGEMENT_REQUEST_DETAIL" minOccurs="0"/>
 *         &lt;element name="DOCUMENT_MANAGEMENT_REQUEST_PRODUCT_DETAIL" type="{http://globalgateway.corelogic.com/order/2015}DOCUMENT_MANAGEMENT_REQUEST_PRODUCT_DETAIL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCUMENT_MANAGEMENT_REQUEST", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "properties",
    "documentmanagementrequestdetail",
    "documentmanagementrequestproductdetail"
})
public class DOCUMENTMANAGEMENTREQUEST {

    @XmlElement(name = "PROPERTIES", namespace = "http://www.mismo.org/residential/2009/schemas")
    protected PROPERTIES properties;
    @XmlElement(name = "DOCUMENT_MANAGEMENT_REQUEST_DETAIL")
    protected DOCUMENTMANAGEMENTREQUESTDETAIL documentmanagementrequestdetail;
    @XmlElement(name = "DOCUMENT_MANAGEMENT_REQUEST_PRODUCT_DETAIL")
    protected DOCUMENTMANAGEMENTREQUESTPRODUCTDETAIL documentmanagementrequestproductdetail;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PROPERTIES }
     *     
     */
    public PROPERTIES getPROPERTIES() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROPERTIES }
     *     
     */
    public void setPROPERTIES(PROPERTIES value) {
        this.properties = value;
    }

    /**
     * Gets the value of the documentmanagementrequestdetail property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTMANAGEMENTREQUESTDETAIL }
     *     
     */
    public DOCUMENTMANAGEMENTREQUESTDETAIL getDOCUMENTMANAGEMENTREQUESTDETAIL() {
        return documentmanagementrequestdetail;
    }

    /**
     * Sets the value of the documentmanagementrequestdetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTMANAGEMENTREQUESTDETAIL }
     *     
     */
    public void setDOCUMENTMANAGEMENTREQUESTDETAIL(DOCUMENTMANAGEMENTREQUESTDETAIL value) {
        this.documentmanagementrequestdetail = value;
    }

    /**
     * Gets the value of the documentmanagementrequestproductdetail property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTMANAGEMENTREQUESTPRODUCTDETAIL }
     *     
     */
    public DOCUMENTMANAGEMENTREQUESTPRODUCTDETAIL getDOCUMENTMANAGEMENTREQUESTPRODUCTDETAIL() {
        return documentmanagementrequestproductdetail;
    }

    /**
     * Sets the value of the documentmanagementrequestproductdetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTMANAGEMENTREQUESTPRODUCTDETAIL }
     *     
     */
    public void setDOCUMENTMANAGEMENTREQUESTPRODUCTDETAIL(DOCUMENTMANAGEMENTREQUESTPRODUCTDETAIL value) {
        this.documentmanagementrequestproductdetail = value;
    }

}
