//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DOCUMENT_MANAGEMENT_RESPONSE_PRODUCT_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCUMENT_MANAGEMENT_RESPONSE_PRODUCT_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentManagementDocumentIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="DocumentManagementResponseProductType" type="{http://globalgateway.corelogic.com/order/2015}DocumentManagementRequestProductEnum" minOccurs="0"/>
 *         &lt;element name="DocumentManagementResponseProductTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="ProductTotalDocumentCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="ProductVersionIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCUMENT_MANAGEMENT_RESPONSE_PRODUCT_DETAIL", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "documentManagementDocumentIdentifier",
    "documentManagementResponseProductType",
    "documentManagementResponseProductTypeOtherDescription",
    "productTotalDocumentCount",
    "productVersionIdentifier"
})
public class DOCUMENTMANAGEMENTRESPONSEPRODUCTDETAIL {

    @XmlElement(name = "DocumentManagementDocumentIdentifier")
    protected MISMOString documentManagementDocumentIdentifier;
    @XmlElement(name = "DocumentManagementResponseProductType")
    protected DocumentManagementRequestProductEnum documentManagementResponseProductType;
    @XmlElement(name = "DocumentManagementResponseProductTypeOtherDescription")
    protected MISMOString documentManagementResponseProductTypeOtherDescription;
    @XmlElement(name = "ProductTotalDocumentCount")
    protected MISMOCount productTotalDocumentCount;
    @XmlElement(name = "ProductVersionIdentifier")
    protected MISMOString productVersionIdentifier;

    /**
     * Gets the value of the documentManagementDocumentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getDocumentManagementDocumentIdentifier() {
        return documentManagementDocumentIdentifier;
    }

    /**
     * Sets the value of the documentManagementDocumentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setDocumentManagementDocumentIdentifier(MISMOString value) {
        this.documentManagementDocumentIdentifier = value;
    }

    /**
     * Gets the value of the documentManagementResponseProductType property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentManagementRequestProductEnum }
     *     
     */
    public DocumentManagementRequestProductEnum getDocumentManagementResponseProductType() {
        return documentManagementResponseProductType;
    }

    /**
     * Sets the value of the documentManagementResponseProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentManagementRequestProductEnum }
     *     
     */
    public void setDocumentManagementResponseProductType(DocumentManagementRequestProductEnum value) {
        this.documentManagementResponseProductType = value;
    }

    /**
     * Gets the value of the documentManagementResponseProductTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getDocumentManagementResponseProductTypeOtherDescription() {
        return documentManagementResponseProductTypeOtherDescription;
    }

    /**
     * Sets the value of the documentManagementResponseProductTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setDocumentManagementResponseProductTypeOtherDescription(MISMOString value) {
        this.documentManagementResponseProductTypeOtherDescription = value;
    }

    /**
     * Gets the value of the productTotalDocumentCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getProductTotalDocumentCount() {
        return productTotalDocumentCount;
    }

    /**
     * Sets the value of the productTotalDocumentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setProductTotalDocumentCount(MISMOCount value) {
        this.productTotalDocumentCount = value;
    }

    /**
     * Gets the value of the productVersionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getProductVersionIdentifier() {
        return productVersionIdentifier;
    }

    /**
     * Sets the value of the productVersionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setProductVersionIdentifier(MISMOString value) {
        this.productVersionIdentifier = value;
    }

}
