//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DOCUMENT_MANAGEMENT_REQUEST_PRODUCT_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DOCUMENT_MANAGEMENT_REQUEST_PRODUCT_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentManagementDocumentIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="DocumentManagementRequestProductType" type="{http://globalgateway.corelogic.com/order/2015}DocumentManagementRequestProductEnum" minOccurs="0"/>
 *         &lt;element name="DocumentManagementRequestProductTypeOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="IncludeSupplementaryDataIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCUMENT_MANAGEMENT_REQUEST_PRODUCT_DETAIL", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "documentManagementDocumentIdentifier",
    "documentManagementRequestProductType",
    "documentManagementRequestProductTypeOtherDescription",
    "includeSupplementaryDataIndicator"
})
public class DOCUMENTMANAGEMENTREQUESTPRODUCTDETAIL {

    @XmlElement(name = "DocumentManagementDocumentIdentifier")
    protected MISMOString documentManagementDocumentIdentifier;
    @XmlElement(name = "DocumentManagementRequestProductType")
    protected DocumentManagementRequestProductEnum documentManagementRequestProductType;
    @XmlElement(name = "DocumentManagementRequestProductTypeOtherDescription")
    protected MISMOString documentManagementRequestProductTypeOtherDescription;
    @XmlElement(name = "IncludeSupplementaryDataIndicator")
    protected MISMOIndicator includeSupplementaryDataIndicator;

    /**
     * Gets the value of the documentManagementDocumentIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getDocumentManagementDocumentIdentifier() {
        return documentManagementDocumentIdentifier;
    }

    /**
     * Sets the value of the documentManagementDocumentIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setDocumentManagementDocumentIdentifier(MISMOString value) {
        this.documentManagementDocumentIdentifier = value;
    }

    /**
     * Gets the value of the documentManagementRequestProductType property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentManagementRequestProductEnum }
     *     
     */
    public DocumentManagementRequestProductEnum getDocumentManagementRequestProductType() {
        return documentManagementRequestProductType;
    }

    /**
     * Sets the value of the documentManagementRequestProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentManagementRequestProductEnum }
     *     
     */
    public void setDocumentManagementRequestProductType(DocumentManagementRequestProductEnum value) {
        this.documentManagementRequestProductType = value;
    }

    /**
     * Gets the value of the documentManagementRequestProductTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getDocumentManagementRequestProductTypeOtherDescription() {
        return documentManagementRequestProductTypeOtherDescription;
    }

    /**
     * Sets the value of the documentManagementRequestProductTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setDocumentManagementRequestProductTypeOtherDescription(MISMOString value) {
        this.documentManagementRequestProductTypeOtherDescription = value;
    }

    /**
     * Gets the value of the includeSupplementaryDataIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getIncludeSupplementaryDataIndicator() {
        return includeSupplementaryDataIndicator;
    }

    /**
     * Sets the value of the includeSupplementaryDataIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setIncludeSupplementaryDataIndicator(MISMOIndicator value) {
        this.includeSupplementaryDataIndicator = value;
    }

}
