//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FOREIGN_OBJECT_CORELOGIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FOREIGN_OBJECT_CORELOGIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eSignVendorNameType" type="{http://globalgateway.corelogic.com/order/2015}eSignVendorNameEnum" minOccurs="0"/>
 *         &lt;element name="eSignVendorNameTypeOtherDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ObjectIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ObjectNameExtensiondIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ObjectNameExtensionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ObjectServiceProductIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FOREIGN_OBJECT_CORELOGIC", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "eSignVendorNameType",
    "eSignVendorNameTypeOtherDescription",
    "objectIdentifier",
    "objectNameExtensiondIdentifier",
    "objectNameExtensionIdentifier",
    "objectServiceProductIdentifier"
})
public class FOREIGNOBJECTCORELOGIC {

    protected ESignVendorNameEnum eSignVendorNameType;
    protected String eSignVendorNameTypeOtherDescription;
    @XmlElement(name = "ObjectIdentifier")
    protected String objectIdentifier;
    @XmlElement(name = "ObjectNameExtensiondIdentifier")
    protected String objectNameExtensiondIdentifier;
    @XmlElement(name = "ObjectNameExtensionIdentifier")
    protected String objectNameExtensionIdentifier;
    @XmlElement(name = "ObjectServiceProductIdentifier")
    protected String objectServiceProductIdentifier;

    /**
     * Gets the value of the eSignVendorNameType property.
     * 
     * @return
     *     possible object is
     *     {@link ESignVendorNameEnum }
     *     
     */
    public ESignVendorNameEnum getESignVendorNameType() {
        return eSignVendorNameType;
    }

    /**
     * Sets the value of the eSignVendorNameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESignVendorNameEnum }
     *     
     */
    public void setESignVendorNameType(ESignVendorNameEnum value) {
        this.eSignVendorNameType = value;
    }

    /**
     * Gets the value of the eSignVendorNameTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESignVendorNameTypeOtherDescription() {
        return eSignVendorNameTypeOtherDescription;
    }

    /**
     * Sets the value of the eSignVendorNameTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESignVendorNameTypeOtherDescription(String value) {
        this.eSignVendorNameTypeOtherDescription = value;
    }

    /**
     * Gets the value of the objectIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectIdentifier() {
        return objectIdentifier;
    }

    /**
     * Sets the value of the objectIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectIdentifier(String value) {
        this.objectIdentifier = value;
    }

    /**
     * Gets the value of the objectNameExtensiondIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectNameExtensiondIdentifier() {
        return objectNameExtensiondIdentifier;
    }

    /**
     * Sets the value of the objectNameExtensiondIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectNameExtensiondIdentifier(String value) {
        this.objectNameExtensiondIdentifier = value;
    }

    /**
     * Gets the value of the objectNameExtensionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectNameExtensionIdentifier() {
        return objectNameExtensionIdentifier;
    }

    /**
     * Sets the value of the objectNameExtensionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectNameExtensionIdentifier(String value) {
        this.objectNameExtensionIdentifier = value;
    }

    /**
     * Gets the value of the objectServiceProductIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectServiceProductIdentifier() {
        return objectServiceProductIdentifier;
    }

    /**
     * Sets the value of the objectServiceProductIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectServiceProductIdentifier(String value) {
        this.objectServiceProductIdentifier = value;
    }

}
