//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FRAUD_ALERT_SET complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FRAUD_ALERT_SET">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FRAUD_ALERT" type="{http://globalgateway.corelogic.com/order/2015}FRAUD_ALERT" minOccurs="0"/>
 *         &lt;element name="FRAUD_ALERT_RECOMMENDATIONS" type="{http://globalgateway.corelogic.com/order/2015}FRAUD_ALERT_RECOMMENDATIONS" minOccurs="0"/>
 *         &lt;element name="FRAUD_ALERT_RESPONSES" type="{http://globalgateway.corelogic.com/order/2015}FRAUD_ALERT_RESPONSES" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FRAUD_ALERT_SET", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "fraudalert",
    "fraudalertrecommendations",
    "fraudalertresponses"
})
public class FRAUDALERTSET {

    @XmlElement(name = "FRAUD_ALERT")
    protected FRAUDALERT fraudalert;
    @XmlElement(name = "FRAUD_ALERT_RECOMMENDATIONS")
    protected FRAUDALERTRECOMMENDATIONS fraudalertrecommendations;
    @XmlElement(name = "FRAUD_ALERT_RESPONSES")
    protected FRAUDALERTRESPONSES fraudalertresponses;

    /**
     * Gets the value of the fraudalert property.
     * 
     * @return
     *     possible object is
     *     {@link FRAUDALERT }
     *     
     */
    public FRAUDALERT getFRAUDALERT() {
        return fraudalert;
    }

    /**
     * Sets the value of the fraudalert property.
     * 
     * @param value
     *     allowed object is
     *     {@link FRAUDALERT }
     *     
     */
    public void setFRAUDALERT(FRAUDALERT value) {
        this.fraudalert = value;
    }

    /**
     * Gets the value of the fraudalertrecommendations property.
     * 
     * @return
     *     possible object is
     *     {@link FRAUDALERTRECOMMENDATIONS }
     *     
     */
    public FRAUDALERTRECOMMENDATIONS getFRAUDALERTRECOMMENDATIONS() {
        return fraudalertrecommendations;
    }

    /**
     * Sets the value of the fraudalertrecommendations property.
     * 
     * @param value
     *     allowed object is
     *     {@link FRAUDALERTRECOMMENDATIONS }
     *     
     */
    public void setFRAUDALERTRECOMMENDATIONS(FRAUDALERTRECOMMENDATIONS value) {
        this.fraudalertrecommendations = value;
    }

    /**
     * Gets the value of the fraudalertresponses property.
     * 
     * @return
     *     possible object is
     *     {@link FRAUDALERTRESPONSES }
     *     
     */
    public FRAUDALERTRESPONSES getFRAUDALERTRESPONSES() {
        return fraudalertresponses;
    }

    /**
     * Sets the value of the fraudalertresponses property.
     * 
     * @param value
     *     allowed object is
     *     {@link FRAUDALERTRESPONSES }
     *     
     */
    public void setFRAUDALERTRESPONSES(FRAUDALERTRESPONSES value) {
        this.fraudalertresponses = value;
    }

}
