//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for INSPECTION_SERVICE_RESPONSE_CORELOGIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INSPECTION_SERVICE_RESPONSE_CORELOGIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CASCADING_AVM_RESULTS" type="{http://globalgateway.corelogic.com/order/2015}CASCADING_AVM_RESULTS" minOccurs="0"/>
 *         &lt;element name="INSPECTION_SERVICE_RESPONSE_PRODUCT_DETAIL" type="{http://globalgateway.corelogic.com/order/2015}INSPECTION_SERVICE_RESPONSE_PRODUCT_DETAIL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INSPECTION_SERVICE_RESPONSE_CORELOGIC", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "cascadingavmresults",
    "inspectionserviceresponseproductdetail"
})
public class INSPECTIONSERVICERESPONSECORELOGIC {

    @XmlElement(name = "CASCADING_AVM_RESULTS")
    protected CASCADINGAVMRESULTS cascadingavmresults;
    @XmlElement(name = "INSPECTION_SERVICE_RESPONSE_PRODUCT_DETAIL")
    protected INSPECTIONSERVICERESPONSEPRODUCTDETAIL inspectionserviceresponseproductdetail;

    /**
     * Gets the value of the cascadingavmresults property.
     * 
     * @return
     *     possible object is
     *     {@link CASCADINGAVMRESULTS }
     *     
     */
    public CASCADINGAVMRESULTS getCASCADINGAVMRESULTS() {
        return cascadingavmresults;
    }

    /**
     * Sets the value of the cascadingavmresults property.
     * 
     * @param value
     *     allowed object is
     *     {@link CASCADINGAVMRESULTS }
     *     
     */
    public void setCASCADINGAVMRESULTS(CASCADINGAVMRESULTS value) {
        this.cascadingavmresults = value;
    }

    /**
     * Gets the value of the inspectionserviceresponseproductdetail property.
     * 
     * @return
     *     possible object is
     *     {@link INSPECTIONSERVICERESPONSEPRODUCTDETAIL }
     *     
     */
    public INSPECTIONSERVICERESPONSEPRODUCTDETAIL getINSPECTIONSERVICERESPONSEPRODUCTDETAIL() {
        return inspectionserviceresponseproductdetail;
    }

    /**
     * Sets the value of the inspectionserviceresponseproductdetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSPECTIONSERVICERESPONSEPRODUCTDETAIL }
     *     
     */
    public void setINSPECTIONSERVICERESPONSEPRODUCTDETAIL(INSPECTIONSERVICERESPONSEPRODUCTDETAIL value) {
        this.inspectionserviceresponseproductdetail = value;
    }

}
