//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MIPremiumSequenceBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MIPremiumSequenceBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="Fifth"/>
 *     &lt;enumeration value="First"/>
 *     &lt;enumeration value="Fourth"/>
 *     &lt;enumeration value="Second"/>
 *     &lt;enumeration value="Third"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MIPremiumSequenceBase")
@XmlEnum
public enum MIPremiumSequenceBase {

    @XmlEnumValue("Fifth")
    FIFTH("Fifth"),
    @XmlEnumValue("First")
    FIRST("First"),
    @XmlEnumValue("Fourth")
    FOURTH("Fourth"),
    @XmlEnumValue("Second")
    SECOND("Second"),
    @XmlEnumValue("Third")
    THIRD("Third");
    private final String value;

    MIPremiumSequenceBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MIPremiumSequenceBase fromValue(String v) {
        for (MIPremiumSequenceBase c: MIPremiumSequenceBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
