//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MortgageHistoryEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MortgageHistoryEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Last"/>
 *     &lt;enumeration value="Prior"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MortgageHistoryEnum", namespace = "http://globalgateway.corelogic.com/order/2015")
@XmlEnum
public enum MortgageHistoryEnum {

    @XmlEnumValue("Last")
    LAST("Last"),
    @XmlEnumValue("Prior")
    PRIOR("Prior");
    private final String value;

    MortgageHistoryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MortgageHistoryEnum fromValue(String v) {
        for (MortgageHistoryEnum c: MortgageHistoryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
