//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderStatusTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OrderStatusTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Confirmed"/>
 *     &lt;enumeration value="Projected"/>
 *     &lt;enumeration value="Estimated"/>
 *     &lt;enumeration value="FullHit"/>
 *     &lt;enumeration value="PartialHit"/>
 *     &lt;enumeration value="EstimatedHit"/>
 *     &lt;enumeration value="NoHit"/>
 *     &lt;enumeration value="Error"/>
 *     &lt;enumeration value="ProductResponseNotYetAvailable"/>
 *     &lt;enumeration value="ProductResponseNoLongerAvailable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OrderStatusTypeEnum", namespace = "http://globalgateway.corelogic.com/order/2015")
@XmlEnum
public enum OrderStatusTypeEnum {

    @XmlEnumValue("Confirmed")
    CONFIRMED("Confirmed"),
    @XmlEnumValue("Projected")
    PROJECTED("Projected"),
    @XmlEnumValue("Estimated")
    ESTIMATED("Estimated"),
    @XmlEnumValue("FullHit")
    FULL_HIT("FullHit"),
    @XmlEnumValue("PartialHit")
    PARTIAL_HIT("PartialHit"),
    @XmlEnumValue("EstimatedHit")
    ESTIMATED_HIT("EstimatedHit"),
    @XmlEnumValue("NoHit")
    NO_HIT("NoHit"),
    @XmlEnumValue("Error")
    ERROR("Error"),
    @XmlEnumValue("ProductResponseNotYetAvailable")
    PRODUCT_RESPONSE_NOT_YET_AVAILABLE("ProductResponseNotYetAvailable"),
    @XmlEnumValue("ProductResponseNoLongerAvailable")
    PRODUCT_RESPONSE_NO_LONGER_AVAILABLE("ProductResponseNoLongerAvailable");
    private final String value;

    OrderStatusTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrderStatusTypeEnum fromValue(String v) {
        for (OrderStatusTypeEnum c: OrderStatusTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
