//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about the parcel. 
 * 
 * <p>Java class for PARCEL_CORELOGIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PARCEL_CORELOGIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ASSESSOR" type="{http://globalgateway.corelogic.com/order/2015}ASSESSOR_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="ASSESSMENT" type="{http://globalgateway.corelogic.com/order/2015}ASSESSMENT_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="ASSESSMENTS" type="{http://globalgateway.corelogic.com/order/2015}ASSESSMENTS_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="EXEMPTIONS" type="{http://globalgateway.corelogic.com/order/2015}EXEMPTIONS_CORELOGIC" minOccurs="0"/>
 *         &lt;element ref="{http://www.mismo.org/residential/2009/schemas}LEGAL_DESCRIPTIONS" minOccurs="0"/>
 *         &lt;element ref="{http://www.mismo.org/residential/2009/schemas}LOCATION_IDENTIFIER" minOccurs="0"/>
 *         &lt;element name="OWNERS" type="{http://globalgateway.corelogic.com/order/2015}OWNERS_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="TAX_LINES" type="{http://globalgateway.corelogic.com/order/2015}TAX_LINES_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="TAX_LINE_SUMMARY" type="{http://globalgateway.corelogic.com/order/2015}TAX_LINE_SUMMARY_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="PARCEL_ADDRESS" type="{http://www.mismo.org/residential/2009/schemas}ADDRESS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PARCEL_CORELOGIC", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "assessor",
    "assessment",
    "assessments",
    "exemptions",
    "legaldescriptions",
    "locationidentifier",
    "owners",
    "taxlines",
    "taxlinesummary",
    "parceladdress"
})
public class PARCELCORELOGIC {

    @XmlElement(name = "ASSESSOR")
    protected ASSESSORCORELOGIC assessor;
    @XmlElement(name = "ASSESSMENT")
    protected ASSESSMENTCORELOGIC assessment;
    @XmlElement(name = "ASSESSMENTS")
    protected ASSESSMENTSCORELOGIC assessments;
    @XmlElement(name = "EXEMPTIONS")
    protected EXEMPTIONSCORELOGIC exemptions;
    @XmlElement(name = "LEGAL_DESCRIPTIONS", namespace = "http://www.mismo.org/residential/2009/schemas")
    protected LEGALDESCRIPTIONS legaldescriptions;
    @XmlElement(name = "LOCATION_IDENTIFIER", namespace = "http://www.mismo.org/residential/2009/schemas")
    protected LOCATIONIDENTIFIER locationidentifier;
    @XmlElement(name = "OWNERS")
    protected OWNERSCORELOGIC owners;
    @XmlElement(name = "TAX_LINES")
    protected TAXLINESCORELOGIC taxlines;
    @XmlElement(name = "TAX_LINE_SUMMARY")
    protected TAXLINESUMMARYCORELOGIC taxlinesummary;
    @XmlElement(name = "PARCEL_ADDRESS")
    protected ADDRESS parceladdress;

    /**
     * Gets the value of the assessor property.
     * 
     * @return
     *     possible object is
     *     {@link ASSESSORCORELOGIC }
     *     
     */
    public ASSESSORCORELOGIC getASSESSOR() {
        return assessor;
    }

    /**
     * Sets the value of the assessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASSESSORCORELOGIC }
     *     
     */
    public void setASSESSOR(ASSESSORCORELOGIC value) {
        this.assessor = value;
    }

    /**
     * Gets the value of the assessment property.
     * 
     * @return
     *     possible object is
     *     {@link ASSESSMENTCORELOGIC }
     *     
     */
    public ASSESSMENTCORELOGIC getASSESSMENT() {
        return assessment;
    }

    /**
     * Sets the value of the assessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASSESSMENTCORELOGIC }
     *     
     */
    public void setASSESSMENT(ASSESSMENTCORELOGIC value) {
        this.assessment = value;
    }

    /**
     * Gets the value of the assessments property.
     * 
     * @return
     *     possible object is
     *     {@link ASSESSMENTSCORELOGIC }
     *     
     */
    public ASSESSMENTSCORELOGIC getASSESSMENTS() {
        return assessments;
    }

    /**
     * Sets the value of the assessments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASSESSMENTSCORELOGIC }
     *     
     */
    public void setASSESSMENTS(ASSESSMENTSCORELOGIC value) {
        this.assessments = value;
    }

    /**
     * Gets the value of the exemptions property.
     * 
     * @return
     *     possible object is
     *     {@link EXEMPTIONSCORELOGIC }
     *     
     */
    public EXEMPTIONSCORELOGIC getEXEMPTIONS() {
        return exemptions;
    }

    /**
     * Sets the value of the exemptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXEMPTIONSCORELOGIC }
     *     
     */
    public void setEXEMPTIONS(EXEMPTIONSCORELOGIC value) {
        this.exemptions = value;
    }

    /**
     * Information regarding the parcel tax legal description of real property 
     * 
     * @return
     *     possible object is
     *     {@link LEGALDESCRIPTIONS }
     *     
     */
    public LEGALDESCRIPTIONS getLEGALDESCRIPTIONS() {
        return legaldescriptions;
    }

    /**
     * Sets the value of the legaldescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEGALDESCRIPTIONS }
     *     
     */
    public void setLEGALDESCRIPTIONS(LEGALDESCRIPTIONS value) {
        this.legaldescriptions = value;
    }

    /**
     * Information regarding the parcel location
     * 
     * @return
     *     possible object is
     *     {@link LOCATIONIDENTIFIER }
     *     
     */
    public LOCATIONIDENTIFIER getLOCATIONIDENTIFIER() {
        return locationidentifier;
    }

    /**
     * Sets the value of the locationidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOCATIONIDENTIFIER }
     *     
     */
    public void setLOCATIONIDENTIFIER(LOCATIONIDENTIFIER value) {
        this.locationidentifier = value;
    }

    /**
     * Gets the value of the owners property.
     * 
     * @return
     *     possible object is
     *     {@link OWNERSCORELOGIC }
     *     
     */
    public OWNERSCORELOGIC getOWNERS() {
        return owners;
    }

    /**
     * Sets the value of the owners property.
     * 
     * @param value
     *     allowed object is
     *     {@link OWNERSCORELOGIC }
     *     
     */
    public void setOWNERS(OWNERSCORELOGIC value) {
        this.owners = value;
    }

    /**
     * Gets the value of the taxlines property.
     * 
     * @return
     *     possible object is
     *     {@link TAXLINESCORELOGIC }
     *     
     */
    public TAXLINESCORELOGIC getTAXLINES() {
        return taxlines;
    }

    /**
     * Sets the value of the taxlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAXLINESCORELOGIC }
     *     
     */
    public void setTAXLINES(TAXLINESCORELOGIC value) {
        this.taxlines = value;
    }

    /**
     * Gets the value of the taxlinesummary property.
     * 
     * @return
     *     possible object is
     *     {@link TAXLINESUMMARYCORELOGIC }
     *     
     */
    public TAXLINESUMMARYCORELOGIC getTAXLINESUMMARY() {
        return taxlinesummary;
    }

    /**
     * Sets the value of the taxlinesummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAXLINESUMMARYCORELOGIC }
     *     
     */
    public void setTAXLINESUMMARY(TAXLINESUMMARYCORELOGIC value) {
        this.taxlinesummary = value;
    }

    /**
     * Gets the value of the parceladdress property.
     * 
     * @return
     *     possible object is
     *     {@link ADDRESS }
     *     
     */
    public ADDRESS getPARCELADDRESS() {
        return parceladdress;
    }

    /**
     * Sets the value of the parceladdress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADDRESS }
     *     
     */
    public void setPARCELADDRESS(ADDRESS value) {
        this.parceladdress = value;
    }

}
