//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PROJECT_OWNERSHIP_ENTITY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROJECT_OWNERSHIP_ENTITY">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SingleEntityOwnershipName" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SingleEntityOwnershipUnitsCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SingleEntityOwnershipOver30DaysDelinquentIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="SingleEntityDeveloperIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="SingleEntityOwnershipUnitsOfTotalPercent" type="{http://www.mismo.org/residential/2009/schemas}MISMOPercent" minOccurs="0"/>
 *         &lt;element name="SingleEntityOwnershipLeasedAtMarketRentCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="SingleEntityOwnershipLeasedUnderRentControlCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SequenceNumber" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROJECT_OWNERSHIP_ENTITY", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "singleEntityOwnershipName",
    "singleEntityOwnershipUnitsCount",
    "singleEntityOwnershipOver30DaysDelinquentIndicator",
    "singleEntityDeveloperIndicator",
    "singleEntityOwnershipUnitsOfTotalPercent",
    "singleEntityOwnershipLeasedAtMarketRentCount",
    "singleEntityOwnershipLeasedUnderRentControlCount"
})
public class PROJECTOWNERSHIPENTITY {

    @XmlElement(name = "SingleEntityOwnershipName")
    protected MISMOString singleEntityOwnershipName;
    @XmlElement(name = "SingleEntityOwnershipUnitsCount")
    protected MISMOString singleEntityOwnershipUnitsCount;
    @XmlElement(name = "SingleEntityOwnershipOver30DaysDelinquentIndicator")
    protected MISMOIndicator singleEntityOwnershipOver30DaysDelinquentIndicator;
    @XmlElement(name = "SingleEntityDeveloperIndicator")
    protected MISMOIndicator singleEntityDeveloperIndicator;
    @XmlElement(name = "SingleEntityOwnershipUnitsOfTotalPercent")
    protected MISMOPercent singleEntityOwnershipUnitsOfTotalPercent;
    @XmlElement(name = "SingleEntityOwnershipLeasedAtMarketRentCount")
    protected MISMOCount singleEntityOwnershipLeasedAtMarketRentCount;
    @XmlElement(name = "SingleEntityOwnershipLeasedUnderRentControlCount")
    protected MISMOCount singleEntityOwnershipLeasedUnderRentControlCount;
    @XmlAttribute(name = "SequenceNumber")
    protected BigInteger sequenceNumber;

    /**
     * Gets the value of the singleEntityOwnershipName property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSingleEntityOwnershipName() {
        return singleEntityOwnershipName;
    }

    /**
     * Sets the value of the singleEntityOwnershipName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSingleEntityOwnershipName(MISMOString value) {
        this.singleEntityOwnershipName = value;
    }

    /**
     * Gets the value of the singleEntityOwnershipUnitsCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSingleEntityOwnershipUnitsCount() {
        return singleEntityOwnershipUnitsCount;
    }

    /**
     * Sets the value of the singleEntityOwnershipUnitsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSingleEntityOwnershipUnitsCount(MISMOString value) {
        this.singleEntityOwnershipUnitsCount = value;
    }

    /**
     * Gets the value of the singleEntityOwnershipOver30DaysDelinquentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getSingleEntityOwnershipOver30DaysDelinquentIndicator() {
        return singleEntityOwnershipOver30DaysDelinquentIndicator;
    }

    /**
     * Sets the value of the singleEntityOwnershipOver30DaysDelinquentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setSingleEntityOwnershipOver30DaysDelinquentIndicator(MISMOIndicator value) {
        this.singleEntityOwnershipOver30DaysDelinquentIndicator = value;
    }

    /**
     * Gets the value of the singleEntityDeveloperIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getSingleEntityDeveloperIndicator() {
        return singleEntityDeveloperIndicator;
    }

    /**
     * Sets the value of the singleEntityDeveloperIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setSingleEntityDeveloperIndicator(MISMOIndicator value) {
        this.singleEntityDeveloperIndicator = value;
    }

    /**
     * Gets the value of the singleEntityOwnershipUnitsOfTotalPercent property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOPercent }
     *     
     */
    public MISMOPercent getSingleEntityOwnershipUnitsOfTotalPercent() {
        return singleEntityOwnershipUnitsOfTotalPercent;
    }

    /**
     * Sets the value of the singleEntityOwnershipUnitsOfTotalPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOPercent }
     *     
     */
    public void setSingleEntityOwnershipUnitsOfTotalPercent(MISMOPercent value) {
        this.singleEntityOwnershipUnitsOfTotalPercent = value;
    }

    /**
     * Gets the value of the singleEntityOwnershipLeasedAtMarketRentCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getSingleEntityOwnershipLeasedAtMarketRentCount() {
        return singleEntityOwnershipLeasedAtMarketRentCount;
    }

    /**
     * Sets the value of the singleEntityOwnershipLeasedAtMarketRentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setSingleEntityOwnershipLeasedAtMarketRentCount(MISMOCount value) {
        this.singleEntityOwnershipLeasedAtMarketRentCount = value;
    }

    /**
     * Gets the value of the singleEntityOwnershipLeasedUnderRentControlCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getSingleEntityOwnershipLeasedUnderRentControlCount() {
        return singleEntityOwnershipLeasedUnderRentControlCount;
    }

    /**
     * Sets the value of the singleEntityOwnershipLeasedUnderRentControlCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setSingleEntityOwnershipLeasedUnderRentControlCount(MISMOCount value) {
        this.singleEntityOwnershipLeasedUnderRentControlCount = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNumber(BigInteger value) {
        this.sequenceNumber = value;
    }

}
