//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PROJECT_OWNERSHIP_CORELOGIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROJECT_OWNERSHIP_CORELOGIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RentalPoolingAgreementIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="RentalPoolingTypeDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="RightOfFirstRefusalIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="RightOfFirstRefusalHOADaysCount" type="{http://www.mismo.org/residential/2009/schemas}MISMOCount" minOccurs="0"/>
 *         &lt;element name="RightOfFirstRefusalForeclosureWaivedIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="DeedRestrictionIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="DeedRestrictionAffordableHousingIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="DeedRestrictionAgeIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="DeedRestrictionPrivateTransferFeeIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="DeedRestrictionOtherIndicator" type="{http://www.mismo.org/residential/2009/schemas}MISMOIndicator" minOccurs="0"/>
 *         &lt;element name="DeedRestrictionOtherDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROJECT_OWNERSHIP_CORELOGIC", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "rentalPoolingAgreementIndicator",
    "rentalPoolingTypeDescription",
    "rightOfFirstRefusalIndicator",
    "rightOfFirstRefusalHOADaysCount",
    "rightOfFirstRefusalForeclosureWaivedIndicator",
    "deedRestrictionIndicator",
    "deedRestrictionAffordableHousingIndicator",
    "deedRestrictionAgeIndicator",
    "deedRestrictionPrivateTransferFeeIndicator",
    "deedRestrictionOtherIndicator",
    "deedRestrictionOtherDescription"
})
public class PROJECTOWNERSHIPCORELOGIC {

    @XmlElement(name = "RentalPoolingAgreementIndicator")
    protected MISMOIndicator rentalPoolingAgreementIndicator;
    @XmlElement(name = "RentalPoolingTypeDescription")
    protected MISMOString rentalPoolingTypeDescription;
    @XmlElement(name = "RightOfFirstRefusalIndicator")
    protected MISMOIndicator rightOfFirstRefusalIndicator;
    @XmlElement(name = "RightOfFirstRefusalHOADaysCount")
    protected MISMOCount rightOfFirstRefusalHOADaysCount;
    @XmlElement(name = "RightOfFirstRefusalForeclosureWaivedIndicator")
    protected MISMOIndicator rightOfFirstRefusalForeclosureWaivedIndicator;
    @XmlElement(name = "DeedRestrictionIndicator")
    protected MISMOIndicator deedRestrictionIndicator;
    @XmlElement(name = "DeedRestrictionAffordableHousingIndicator")
    protected MISMOIndicator deedRestrictionAffordableHousingIndicator;
    @XmlElement(name = "DeedRestrictionAgeIndicator")
    protected MISMOIndicator deedRestrictionAgeIndicator;
    @XmlElement(name = "DeedRestrictionPrivateTransferFeeIndicator")
    protected MISMOIndicator deedRestrictionPrivateTransferFeeIndicator;
    @XmlElement(name = "DeedRestrictionOtherIndicator")
    protected MISMOIndicator deedRestrictionOtherIndicator;
    @XmlElement(name = "DeedRestrictionOtherDescription")
    protected MISMOString deedRestrictionOtherDescription;

    /**
     * Gets the value of the rentalPoolingAgreementIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getRentalPoolingAgreementIndicator() {
        return rentalPoolingAgreementIndicator;
    }

    /**
     * Sets the value of the rentalPoolingAgreementIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setRentalPoolingAgreementIndicator(MISMOIndicator value) {
        this.rentalPoolingAgreementIndicator = value;
    }

    /**
     * Gets the value of the rentalPoolingTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getRentalPoolingTypeDescription() {
        return rentalPoolingTypeDescription;
    }

    /**
     * Sets the value of the rentalPoolingTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setRentalPoolingTypeDescription(MISMOString value) {
        this.rentalPoolingTypeDescription = value;
    }

    /**
     * Gets the value of the rightOfFirstRefusalIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getRightOfFirstRefusalIndicator() {
        return rightOfFirstRefusalIndicator;
    }

    /**
     * Sets the value of the rightOfFirstRefusalIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setRightOfFirstRefusalIndicator(MISMOIndicator value) {
        this.rightOfFirstRefusalIndicator = value;
    }

    /**
     * Gets the value of the rightOfFirstRefusalHOADaysCount property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOCount }
     *     
     */
    public MISMOCount getRightOfFirstRefusalHOADaysCount() {
        return rightOfFirstRefusalHOADaysCount;
    }

    /**
     * Sets the value of the rightOfFirstRefusalHOADaysCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOCount }
     *     
     */
    public void setRightOfFirstRefusalHOADaysCount(MISMOCount value) {
        this.rightOfFirstRefusalHOADaysCount = value;
    }

    /**
     * Gets the value of the rightOfFirstRefusalForeclosureWaivedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getRightOfFirstRefusalForeclosureWaivedIndicator() {
        return rightOfFirstRefusalForeclosureWaivedIndicator;
    }

    /**
     * Sets the value of the rightOfFirstRefusalForeclosureWaivedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setRightOfFirstRefusalForeclosureWaivedIndicator(MISMOIndicator value) {
        this.rightOfFirstRefusalForeclosureWaivedIndicator = value;
    }

    /**
     * Gets the value of the deedRestrictionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getDeedRestrictionIndicator() {
        return deedRestrictionIndicator;
    }

    /**
     * Sets the value of the deedRestrictionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setDeedRestrictionIndicator(MISMOIndicator value) {
        this.deedRestrictionIndicator = value;
    }

    /**
     * Gets the value of the deedRestrictionAffordableHousingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getDeedRestrictionAffordableHousingIndicator() {
        return deedRestrictionAffordableHousingIndicator;
    }

    /**
     * Sets the value of the deedRestrictionAffordableHousingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setDeedRestrictionAffordableHousingIndicator(MISMOIndicator value) {
        this.deedRestrictionAffordableHousingIndicator = value;
    }

    /**
     * Gets the value of the deedRestrictionAgeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getDeedRestrictionAgeIndicator() {
        return deedRestrictionAgeIndicator;
    }

    /**
     * Sets the value of the deedRestrictionAgeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setDeedRestrictionAgeIndicator(MISMOIndicator value) {
        this.deedRestrictionAgeIndicator = value;
    }

    /**
     * Gets the value of the deedRestrictionPrivateTransferFeeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getDeedRestrictionPrivateTransferFeeIndicator() {
        return deedRestrictionPrivateTransferFeeIndicator;
    }

    /**
     * Sets the value of the deedRestrictionPrivateTransferFeeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setDeedRestrictionPrivateTransferFeeIndicator(MISMOIndicator value) {
        this.deedRestrictionPrivateTransferFeeIndicator = value;
    }

    /**
     * Gets the value of the deedRestrictionOtherIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOIndicator }
     *     
     */
    public MISMOIndicator getDeedRestrictionOtherIndicator() {
        return deedRestrictionOtherIndicator;
    }

    /**
     * Sets the value of the deedRestrictionOtherIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOIndicator }
     *     
     */
    public void setDeedRestrictionOtherIndicator(MISMOIndicator value) {
        this.deedRestrictionOtherIndicator = value;
    }

    /**
     * Gets the value of the deedRestrictionOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getDeedRestrictionOtherDescription() {
        return deedRestrictionOtherDescription;
    }

    /**
     * Sets the value of the deedRestrictionOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setDeedRestrictionOtherDescription(MISMOString value) {
        this.deedRestrictionOtherDescription = value;
    }

}
