//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REQUESTING_PARTY_CORELOGIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REQUESTING_PARTY_CORELOGIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlertServiceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="JobIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServicerIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LoginAccountIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LoginAccountPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REQUESTING_PARTY_CORELOGIC", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "alertServiceIdentifier",
    "jobIdentifier",
    "servicerIdentifier",
    "loginAccountIdentifier",
    "loginAccountPassword"
})
public class REQUESTINGPARTYCORELOGIC {

    @XmlElement(name = "AlertServiceIdentifier")
    protected String alertServiceIdentifier;
    @XmlElement(name = "JobIdentifier")
    protected String jobIdentifier;
    @XmlElement(name = "ServicerIdentifier")
    protected String servicerIdentifier;
    @XmlElement(name = "LoginAccountIdentifier")
    protected String loginAccountIdentifier;
    @XmlElement(name = "LoginAccountPassword")
    protected String loginAccountPassword;

    /**
     * Gets the value of the alertServiceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertServiceIdentifier() {
        return alertServiceIdentifier;
    }

    /**
     * Sets the value of the alertServiceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertServiceIdentifier(String value) {
        this.alertServiceIdentifier = value;
    }

    /**
     * Gets the value of the jobIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobIdentifier() {
        return jobIdentifier;
    }

    /**
     * Sets the value of the jobIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobIdentifier(String value) {
        this.jobIdentifier = value;
    }

    /**
     * Gets the value of the servicerIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicerIdentifier() {
        return servicerIdentifier;
    }

    /**
     * Sets the value of the servicerIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicerIdentifier(String value) {
        this.servicerIdentifier = value;
    }

    /**
     * Gets the value of the loginAccountIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginAccountIdentifier() {
        return loginAccountIdentifier;
    }

    /**
     * Sets the value of the loginAccountIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginAccountIdentifier(String value) {
        this.loginAccountIdentifier = value;
    }

    /**
     * Gets the value of the loginAccountPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginAccountPassword() {
        return loginAccountPassword;
    }

    /**
     * Sets the value of the loginAccountPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginAccountPassword(String value) {
        this.loginAccountPassword = value;
    }

}
