//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:53:09 AM CAT 
//


package qubed.corelogicextensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VALUATION_REQUEST_COMPARABLE_SEARCH_LAND_USE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VALUATION_REQUEST_COMPARABLE_SEARCH_LAND_USE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResidentialType" type="{http://globalgateway.corelogic.com/order/2015}ResidentialEnum" minOccurs="0"/>
 *         &lt;element name="ResidentialIncomeAndOtherType" type="{http://globalgateway.corelogic.com/order/2015}ResidentialIncomeAndOtherEnum" minOccurs="0"/>
 *         &lt;element name="CommercialType" type="{http://globalgateway.corelogic.com/order/2015}CommercialEnum" minOccurs="0"/>
 *         &lt;element name="IndustrialType" type="{http://globalgateway.corelogic.com/order/2015}IndustrialEnum" minOccurs="0"/>
 *         &lt;element name="VacantLandType" type="{http://globalgateway.corelogic.com/order/2015}VacantLandEnum" minOccurs="0"/>
 *         &lt;element name="AgriculturalType" type="{http://globalgateway.corelogic.com/order/2015}AgriculturalEnum" minOccurs="0"/>
 *         &lt;element name="PublicAndSemiPublicType" type="{http://globalgateway.corelogic.com/order/2015}PublicAndSemiPublicEnum" minOccurs="0"/>
 *         &lt;element name="RecreationalType" type="{http://globalgateway.corelogic.com/order/2015}RecreationalEnum" minOccurs="0"/>
 *         &lt;element name="TransportationAndUtilityType" type="{http://globalgateway.corelogic.com/order/2015}TransportationAndUtilityEnum" minOccurs="0"/>
 *         &lt;element name="SameAsSubjectType" type="{http://globalgateway.corelogic.com/order/2015}SameAsSubjectEnum" minOccurs="0"/>
 *         &lt;element name="OtherLandUseDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NewConstruction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreviouslyOccupied" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Unknown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VALUATION_REQUEST_COMPARABLE_SEARCH_LAND_USE", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "residentialType",
    "residentialIncomeAndOtherType",
    "commercialType",
    "industrialType",
    "vacantLandType",
    "agriculturalType",
    "publicAndSemiPublicType",
    "recreationalType",
    "transportationAndUtilityType",
    "sameAsSubjectType",
    "otherLandUseDescription",
    "newConstruction",
    "previouslyOccupied",
    "unknown"
})
public class VALUATIONREQUESTCOMPARABLESEARCHLANDUSE {

    @XmlElement(name = "ResidentialType")
    protected ResidentialEnum residentialType;
    @XmlElement(name = "ResidentialIncomeAndOtherType")
    protected String residentialIncomeAndOtherType;
    @XmlElement(name = "CommercialType")
    protected CommercialEnum commercialType;
    @XmlElement(name = "IndustrialType")
    protected IndustrialEnum industrialType;
    @XmlElement(name = "VacantLandType")
    protected VacantLandEnum vacantLandType;
    @XmlElement(name = "AgriculturalType")
    protected AgriculturalEnum agriculturalType;
    @XmlElement(name = "PublicAndSemiPublicType")
    protected PublicAndSemiPublicEnum publicAndSemiPublicType;
    @XmlElement(name = "RecreationalType")
    protected RecreationalEnum recreationalType;
    @XmlElement(name = "TransportationAndUtilityType")
    protected TransportationAndUtilityEnum transportationAndUtilityType;
    @XmlElement(name = "SameAsSubjectType")
    protected SameAsSubjectEnum sameAsSubjectType;
    @XmlElement(name = "OtherLandUseDescription")
    protected String otherLandUseDescription;
    @XmlElement(name = "NewConstruction")
    protected String newConstruction;
    @XmlElement(name = "PreviouslyOccupied")
    protected String previouslyOccupied;
    @XmlElement(name = "Unknown")
    protected String unknown;

    /**
     * Gets the value of the residentialType property.
     * 
     * @return
     *     possible object is
     *     {@link ResidentialEnum }
     *     
     */
    public ResidentialEnum getResidentialType() {
        return residentialType;
    }

    /**
     * Sets the value of the residentialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResidentialEnum }
     *     
     */
    public void setResidentialType(ResidentialEnum value) {
        this.residentialType = value;
    }

    /**
     * Gets the value of the residentialIncomeAndOtherType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidentialIncomeAndOtherType() {
        return residentialIncomeAndOtherType;
    }

    /**
     * Sets the value of the residentialIncomeAndOtherType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidentialIncomeAndOtherType(String value) {
        this.residentialIncomeAndOtherType = value;
    }

    /**
     * Gets the value of the commercialType property.
     * 
     * @return
     *     possible object is
     *     {@link CommercialEnum }
     *     
     */
    public CommercialEnum getCommercialType() {
        return commercialType;
    }

    /**
     * Sets the value of the commercialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommercialEnum }
     *     
     */
    public void setCommercialType(CommercialEnum value) {
        this.commercialType = value;
    }

    /**
     * Gets the value of the industrialType property.
     * 
     * @return
     *     possible object is
     *     {@link IndustrialEnum }
     *     
     */
    public IndustrialEnum getIndustrialType() {
        return industrialType;
    }

    /**
     * Sets the value of the industrialType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndustrialEnum }
     *     
     */
    public void setIndustrialType(IndustrialEnum value) {
        this.industrialType = value;
    }

    /**
     * Gets the value of the vacantLandType property.
     * 
     * @return
     *     possible object is
     *     {@link VacantLandEnum }
     *     
     */
    public VacantLandEnum getVacantLandType() {
        return vacantLandType;
    }

    /**
     * Sets the value of the vacantLandType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VacantLandEnum }
     *     
     */
    public void setVacantLandType(VacantLandEnum value) {
        this.vacantLandType = value;
    }

    /**
     * Gets the value of the agriculturalType property.
     * 
     * @return
     *     possible object is
     *     {@link AgriculturalEnum }
     *     
     */
    public AgriculturalEnum getAgriculturalType() {
        return agriculturalType;
    }

    /**
     * Sets the value of the agriculturalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgriculturalEnum }
     *     
     */
    public void setAgriculturalType(AgriculturalEnum value) {
        this.agriculturalType = value;
    }

    /**
     * Gets the value of the publicAndSemiPublicType property.
     * 
     * @return
     *     possible object is
     *     {@link PublicAndSemiPublicEnum }
     *     
     */
    public PublicAndSemiPublicEnum getPublicAndSemiPublicType() {
        return publicAndSemiPublicType;
    }

    /**
     * Sets the value of the publicAndSemiPublicType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicAndSemiPublicEnum }
     *     
     */
    public void setPublicAndSemiPublicType(PublicAndSemiPublicEnum value) {
        this.publicAndSemiPublicType = value;
    }

    /**
     * Gets the value of the recreationalType property.
     * 
     * @return
     *     possible object is
     *     {@link RecreationalEnum }
     *     
     */
    public RecreationalEnum getRecreationalType() {
        return recreationalType;
    }

    /**
     * Sets the value of the recreationalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecreationalEnum }
     *     
     */
    public void setRecreationalType(RecreationalEnum value) {
        this.recreationalType = value;
    }

    /**
     * Gets the value of the transportationAndUtilityType property.
     * 
     * @return
     *     possible object is
     *     {@link TransportationAndUtilityEnum }
     *     
     */
    public TransportationAndUtilityEnum getTransportationAndUtilityType() {
        return transportationAndUtilityType;
    }

    /**
     * Sets the value of the transportationAndUtilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportationAndUtilityEnum }
     *     
     */
    public void setTransportationAndUtilityType(TransportationAndUtilityEnum value) {
        this.transportationAndUtilityType = value;
    }

    /**
     * Gets the value of the sameAsSubjectType property.
     * 
     * @return
     *     possible object is
     *     {@link SameAsSubjectEnum }
     *     
     */
    public SameAsSubjectEnum getSameAsSubjectType() {
        return sameAsSubjectType;
    }

    /**
     * Sets the value of the sameAsSubjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SameAsSubjectEnum }
     *     
     */
    public void setSameAsSubjectType(SameAsSubjectEnum value) {
        this.sameAsSubjectType = value;
    }

    /**
     * Gets the value of the otherLandUseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherLandUseDescription() {
        return otherLandUseDescription;
    }

    /**
     * Sets the value of the otherLandUseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherLandUseDescription(String value) {
        this.otherLandUseDescription = value;
    }

    /**
     * Gets the value of the newConstruction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewConstruction() {
        return newConstruction;
    }

    /**
     * Sets the value of the newConstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewConstruction(String value) {
        this.newConstruction = value;
    }

    /**
     * Gets the value of the previouslyOccupied property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviouslyOccupied() {
        return previouslyOccupied;
    }

    /**
     * Sets the value of the previouslyOccupied property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviouslyOccupied(String value) {
        this.previouslyOccupied = value;
    }

    /**
     * Gets the value of the unknown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnknown() {
        return unknown;
    }

    /**
     * Sets the value of the unknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnknown(String value) {
        this.unknown = value;
    }

}
