//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CarStorageBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CarStorageBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="Carport"/>
 *     &lt;enumeration value="Covered"/>
 *     &lt;enumeration value="Driveway"/>
 *     &lt;enumeration value="Garage"/>
 *     &lt;enumeration value="OffStreet"/>
 *     &lt;enumeration value="Open"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CarStorageBase")
@XmlEnum
public enum CarStorageBase {

    @XmlEnumValue("Carport")
    CARPORT("Carport"),
    @XmlEnumValue("Covered")
    COVERED("Covered"),
    @XmlEnumValue("Driveway")
    DRIVEWAY("Driveway"),
    @XmlEnumValue("Garage")
    GARAGE("Garage"),
    @XmlEnumValue("OffStreet")
    OFF_STREET("OffStreet"),
    @XmlEnumValue("Open")
    OPEN("Open"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    CarStorageBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CarStorageBase fromValue(String v) {
        for (CarStorageBase c: CarStorageBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
