//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentStatusTimeframeBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComponentStatusTimeframeBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="ElevenToFifteenYears"/>
 *     &lt;enumeration value="LessThanOneYear"/>
 *     &lt;enumeration value="OneToFiveYears"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="SixToTenYears"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ComponentStatusTimeframeBase")
@XmlEnum
public enum ComponentStatusTimeframeBase {

    @XmlEnumValue("ElevenToFifteenYears")
    ELEVEN_TO_FIFTEEN_YEARS("ElevenToFifteenYears"),
    @XmlEnumValue("LessThanOneYear")
    LESS_THAN_ONE_YEAR("LessThanOneYear"),
    @XmlEnumValue("OneToFiveYears")
    ONE_TO_FIVE_YEARS("OneToFiveYears"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("SixToTenYears")
    SIX_TO_TEN_YEARS("SixToTenYears"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    ComponentStatusTimeframeBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComponentStatusTimeframeBase fromValue(String v) {
        for (ComponentStatusTimeframeBase c: ComponentStatusTimeframeBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
