//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FRAUD_ALERT_RECOMMENDATION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FRAUD_ALERT_RECOMMENDATION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecommendationChecked" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecommendationMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FRAUD_ALERT_RECOMMENDATION", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "recommendationChecked",
    "recommendationMessage"
})
public class FRAUDALERTRECOMMENDATION {

    @XmlElement(name = "RecommendationChecked")
    protected String recommendationChecked;
    @XmlElement(name = "RecommendationMessage")
    protected String recommendationMessage;

    /**
     * Gets the value of the recommendationChecked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendationChecked() {
        return recommendationChecked;
    }

    /**
     * Sets the value of the recommendationChecked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendationChecked(String value) {
        this.recommendationChecked = value;
    }

    /**
     * Gets the value of the recommendationMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendationMessage() {
        return recommendationMessage;
    }

    /**
     * Sets the value of the recommendationMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendationMessage(String value) {
        this.recommendationMessage = value;
    }

}
