//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FRAUD_RESPONSE_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FRAUD_RESPONSE_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportFirstIssuedDatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ReportIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportLastUpdatedDatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ReportRunDatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ReportTransactionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportTypeOtherDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RiptReportIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CollateralRiskScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AppraisalDateDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AppraisalSubjectPropertyAppraisedValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AppraisalSubjectPropertyAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValuationCertaintylsGranularScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValuationCertaintyFinalScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AppraisalIntegrityFinalModelScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AvmDataRavePropertyComplexityScore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FRAUD_RESPONSE_DETAIL", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "reportFirstIssuedDatetime",
    "reportIdentifier",
    "reportLastUpdatedDatetime",
    "reportRunDatetime",
    "reportTransactionIdentifier",
    "reportType",
    "reportTypeOtherDescription",
    "riptReportIdentifier",
    "fraudScore",
    "collateralRiskScore",
    "appraisalDateDescription",
    "appraisalSubjectPropertyAppraisedValue",
    "appraisalSubjectPropertyAddress",
    "valuationCertaintylsGranularScore",
    "valuationCertaintyFinalScore",
    "appraisalIntegrityFinalModelScore",
    "avmDataRavePropertyComplexityScore"
})
public class FRAUDRESPONSEDETAIL {

    @XmlElementRef(name = "ReportFirstIssuedDatetime", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> reportFirstIssuedDatetime;
    @XmlElementRef(name = "ReportIdentifier", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> reportIdentifier;
    @XmlElementRef(name = "ReportLastUpdatedDatetime", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> reportLastUpdatedDatetime;
    @XmlElementRef(name = "ReportRunDatetime", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> reportRunDatetime;
    @XmlElementRef(name = "ReportTransactionIdentifier", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> reportTransactionIdentifier;
    @XmlElementRef(name = "ReportType", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> reportType;
    @XmlElementRef(name = "ReportTypeOtherDescription", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> reportTypeOtherDescription;
    @XmlElementRef(name = "RiptReportIdentifier", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> riptReportIdentifier;
    @XmlElementRef(name = "FraudScore", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fraudScore;
    @XmlElementRef(name = "CollateralRiskScore", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> collateralRiskScore;
    @XmlElementRef(name = "AppraisalDateDescription", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> appraisalDateDescription;
    @XmlElementRef(name = "AppraisalSubjectPropertyAppraisedValue", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> appraisalSubjectPropertyAppraisedValue;
    @XmlElementRef(name = "AppraisalSubjectPropertyAddress", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> appraisalSubjectPropertyAddress;
    @XmlElementRef(name = "ValuationCertaintylsGranularScore", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> valuationCertaintylsGranularScore;
    @XmlElementRef(name = "ValuationCertaintyFinalScore", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> valuationCertaintyFinalScore;
    @XmlElementRef(name = "AppraisalIntegrityFinalModelScore", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> appraisalIntegrityFinalModelScore;
    @XmlElementRef(name = "AvmDataRavePropertyComplexityScore", namespace = "http://globalgateway.corelogic.com/order/2015", type = JAXBElement.class, required = false)
    protected JAXBElement<String> avmDataRavePropertyComplexityScore;

    /**
     * Gets the value of the reportFirstIssuedDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getReportFirstIssuedDatetime() {
        return reportFirstIssuedDatetime;
    }

    /**
     * Sets the value of the reportFirstIssuedDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setReportFirstIssuedDatetime(JAXBElement<XMLGregorianCalendar> value) {
        this.reportFirstIssuedDatetime = value;
    }

    /**
     * Gets the value of the reportIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReportIdentifier() {
        return reportIdentifier;
    }

    /**
     * Sets the value of the reportIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReportIdentifier(JAXBElement<String> value) {
        this.reportIdentifier = value;
    }

    /**
     * Gets the value of the reportLastUpdatedDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getReportLastUpdatedDatetime() {
        return reportLastUpdatedDatetime;
    }

    /**
     * Sets the value of the reportLastUpdatedDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setReportLastUpdatedDatetime(JAXBElement<XMLGregorianCalendar> value) {
        this.reportLastUpdatedDatetime = value;
    }

    /**
     * Gets the value of the reportRunDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getReportRunDatetime() {
        return reportRunDatetime;
    }

    /**
     * Sets the value of the reportRunDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setReportRunDatetime(JAXBElement<XMLGregorianCalendar> value) {
        this.reportRunDatetime = value;
    }

    /**
     * Gets the value of the reportTransactionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReportTransactionIdentifier() {
        return reportTransactionIdentifier;
    }

    /**
     * Sets the value of the reportTransactionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReportTransactionIdentifier(JAXBElement<String> value) {
        this.reportTransactionIdentifier = value;
    }

    /**
     * Gets the value of the reportType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReportType() {
        return reportType;
    }

    /**
     * Sets the value of the reportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReportType(JAXBElement<String> value) {
        this.reportType = value;
    }

    /**
     * Gets the value of the reportTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReportTypeOtherDescription() {
        return reportTypeOtherDescription;
    }

    /**
     * Sets the value of the reportTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReportTypeOtherDescription(JAXBElement<String> value) {
        this.reportTypeOtherDescription = value;
    }

    /**
     * Gets the value of the riptReportIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRiptReportIdentifier() {
        return riptReportIdentifier;
    }

    /**
     * Sets the value of the riptReportIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRiptReportIdentifier(JAXBElement<String> value) {
        this.riptReportIdentifier = value;
    }

    /**
     * Gets the value of the fraudScore property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFraudScore() {
        return fraudScore;
    }

    /**
     * Sets the value of the fraudScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFraudScore(JAXBElement<String> value) {
        this.fraudScore = value;
    }

    /**
     * Gets the value of the collateralRiskScore property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCollateralRiskScore() {
        return collateralRiskScore;
    }

    /**
     * Sets the value of the collateralRiskScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCollateralRiskScore(JAXBElement<String> value) {
        this.collateralRiskScore = value;
    }

    /**
     * Gets the value of the appraisalDateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAppraisalDateDescription() {
        return appraisalDateDescription;
    }

    /**
     * Sets the value of the appraisalDateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAppraisalDateDescription(JAXBElement<String> value) {
        this.appraisalDateDescription = value;
    }

    /**
     * Gets the value of the appraisalSubjectPropertyAppraisedValue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAppraisalSubjectPropertyAppraisedValue() {
        return appraisalSubjectPropertyAppraisedValue;
    }

    /**
     * Sets the value of the appraisalSubjectPropertyAppraisedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAppraisalSubjectPropertyAppraisedValue(JAXBElement<String> value) {
        this.appraisalSubjectPropertyAppraisedValue = value;
    }

    /**
     * Gets the value of the appraisalSubjectPropertyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAppraisalSubjectPropertyAddress() {
        return appraisalSubjectPropertyAddress;
    }

    /**
     * Sets the value of the appraisalSubjectPropertyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAppraisalSubjectPropertyAddress(JAXBElement<String> value) {
        this.appraisalSubjectPropertyAddress = value;
    }

    /**
     * Gets the value of the valuationCertaintylsGranularScore property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getValuationCertaintylsGranularScore() {
        return valuationCertaintylsGranularScore;
    }

    /**
     * Sets the value of the valuationCertaintylsGranularScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setValuationCertaintylsGranularScore(JAXBElement<String> value) {
        this.valuationCertaintylsGranularScore = value;
    }

    /**
     * Gets the value of the valuationCertaintyFinalScore property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getValuationCertaintyFinalScore() {
        return valuationCertaintyFinalScore;
    }

    /**
     * Sets the value of the valuationCertaintyFinalScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setValuationCertaintyFinalScore(JAXBElement<String> value) {
        this.valuationCertaintyFinalScore = value;
    }

    /**
     * Gets the value of the appraisalIntegrityFinalModelScore property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAppraisalIntegrityFinalModelScore() {
        return appraisalIntegrityFinalModelScore;
    }

    /**
     * Sets the value of the appraisalIntegrityFinalModelScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAppraisalIntegrityFinalModelScore(JAXBElement<String> value) {
        this.appraisalIntegrityFinalModelScore = value;
    }

    /**
     * Gets the value of the avmDataRavePropertyComplexityScore property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAvmDataRavePropertyComplexityScore() {
        return avmDataRavePropertyComplexityScore;
    }

    /**
     * Sets the value of the avmDataRavePropertyComplexityScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAvmDataRavePropertyComplexityScore(JAXBElement<String> value) {
        this.avmDataRavePropertyComplexityScore = value;
    }

}
