//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GFEComparisonBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GFEComparisonBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="NotApplicable"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="SameLoanWithLowerInterestRate"/>
 *     &lt;enumeration value="SameLoanWithLowerSettlementCharges"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GFEComparisonBase")
@XmlEnum
public enum GFEComparisonBase {

    @XmlEnumValue("NotApplicable")
    NOT_APPLICABLE("NotApplicable"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("SameLoanWithLowerInterestRate")
    SAME_LOAN_WITH_LOWER_INTEREST_RATE("SameLoanWithLowerInterestRate"),
    @XmlEnumValue("SameLoanWithLowerSettlementCharges")
    SAME_LOAN_WITH_LOWER_SETTLEMENT_CHARGES("SameLoanWithLowerSettlementCharges");
    private final String value;

    GFEComparisonBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GFEComparisonBase fromValue(String v) {
        for (GFEComparisonBase c: GFEComparisonBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
