//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MICertificateBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MICertificateBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="BothPrimaryAndPool"/>
 *     &lt;enumeration value="NoCoverage"/>
 *     &lt;enumeration value="Pool"/>
 *     &lt;enumeration value="Primary"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MICertificateBase")
@XmlEnum
public enum MICertificateBase {

    @XmlEnumValue("BothPrimaryAndPool")
    BOTH_PRIMARY_AND_POOL("BothPrimaryAndPool"),
    @XmlEnumValue("NoCoverage")
    NO_COVERAGE("NoCoverage"),
    @XmlEnumValue("Pool")
    POOL("Pool"),
    @XmlEnumValue("Primary")
    PRIMARY("Primary");
    private final String value;

    MICertificateBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MICertificateBase fromValue(String v) {
        for (MICertificateBase c: MICertificateBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
