//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OrderTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Appraisal"/>
 *     &lt;enumeration value="Flood"/>
 *     &lt;enumeration value="Heartbeat"/>
 *     &lt;enumeration value="Risk"/>
 *     &lt;enumeration value="Risk2"/>
 *     &lt;enumeration value="Tax"/>
 *     &lt;enumeration value="Title"/>
 *     &lt;enumeration value="VOI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OrderTypeEnum", namespace = "http://globalgateway.corelogic.com/order/2015")
@XmlEnum
public enum OrderTypeEnum {


    /**
     * Appraisal 
     * 
     */
    @XmlEnumValue("Appraisal")
    APPRAISAL("Appraisal"),

    /**
     *  Flood 
     * 
     */
    @XmlEnumValue("Flood")
    FLOOD("Flood"),

    /**
     *  Heartbeat 
     * 
     */
    @XmlEnumValue("Heartbeat")
    HEARTBEAT("Heartbeat"),

    /**
     *  Risk 
     * 
     */
    @XmlEnumValue("Risk")
    RISK("Risk"),

    /**
     *  Collateral Manager 
     * 
     */
    @XmlEnumValue("Risk2")
    RISK_2("Risk2"),

    /**
     *  Tax 
     * 
     */
    @XmlEnumValue("Tax")
    TAX("Tax"),

    /**
     *  Title 
     * 
     */
    @XmlEnumValue("Title")
    TITLE("Title"),

    /**
     *  VOI 
     * 
     */
    VOI("VOI");
    private final String value;

    OrderTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrderTypeEnum fromValue(String v) {
        for (OrderTypeEnum c: OrderTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
