//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PresumptionOfComplianceBase.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PresumptionOfComplianceBase">
 *   &lt;restriction base="{http://www.mismo.org/residential/2009/schemas}MISMOEnum_Base">
 *     &lt;enumeration value="RebuttablePresumption"/>
 *     &lt;enumeration value="SafeHarbor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PresumptionOfComplianceBase")
@XmlEnum
public enum PresumptionOfComplianceBase {


    /**
     * Presumed compliance that creditor has followed or met certain requirements related to the borrower's ability to repay.
     * 
     */
    @XmlEnumValue("RebuttablePresumption")
    REBUTTABLE_PRESUMPTION("RebuttablePresumption"),

    /**
     * The transaction meets Regulation Z Qualified Mortgage Safe Harbor threshold.
     * 
     */
    @XmlEnumValue("SafeHarbor")
    SAFE_HARBOR("SafeHarbor");
    private final String value;

    PresumptionOfComplianceBase(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PresumptionOfComplianceBase fromValue(String v) {
        for (PresumptionOfComplianceBase c: PresumptionOfComplianceBase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
