//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PublicAndSemiPublicEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PublicAndSemiPublicEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AllPublicAndSemiPublicTypes"/>
 *     &lt;enumeration value="Public"/>
 *     &lt;enumeration value="TaxExempt"/>
 *     &lt;enumeration value="StateProperty"/>
 *     &lt;enumeration value="CountyProperty"/>
 *     &lt;enumeration value="MunicipalProperty"/>
 *     &lt;enumeration value="Police_Fire_CivilDefense"/>
 *     &lt;enumeration value="Embassies_Chanceries"/>
 *     &lt;enumeration value="CorrectionalFacility"/>
 *     &lt;enumeration value="CommunityCenter"/>
 *     &lt;enumeration value="HistoricalDistrict"/>
 *     &lt;enumeration value="FederalBuilding"/>
 *     &lt;enumeration value="IndianReservation"/>
 *     &lt;enumeration value="Art"/>
 *     &lt;enumeration value="MilitaryBuilding"/>
 *     &lt;enumeration value="PossessoryInterest"/>
 *     &lt;enumeration value="NurserySchool"/>
 *     &lt;enumeration value="HighSchool"/>
 *     &lt;enumeration value="PrivateSchool"/>
 *     &lt;enumeration value="Vocational_TradeSchool"/>
 *     &lt;enumeration value="EducationalService"/>
 *     &lt;enumeration value="SecondaryEducationalSchool"/>
 *     &lt;enumeration value="PublicSchool"/>
 *     &lt;enumeration value="PublicService"/>
 *     &lt;enumeration value="Charity"/>
 *     &lt;enumeration value="Religious"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PublicAndSemiPublicEnum", namespace = "http://globalgateway.corelogic.com/order/2015")
@XmlEnum
public enum PublicAndSemiPublicEnum {

    @XmlEnumValue("AllPublicAndSemiPublicTypes")
    ALL_PUBLIC_AND_SEMI_PUBLIC_TYPES("AllPublicAndSemiPublicTypes"),
    @XmlEnumValue("Public")
    PUBLIC("Public"),
    @XmlEnumValue("TaxExempt")
    TAX_EXEMPT("TaxExempt"),
    @XmlEnumValue("StateProperty")
    STATE_PROPERTY("StateProperty"),
    @XmlEnumValue("CountyProperty")
    COUNTY_PROPERTY("CountyProperty"),
    @XmlEnumValue("MunicipalProperty")
    MUNICIPAL_PROPERTY("MunicipalProperty"),
    @XmlEnumValue("Police_Fire_CivilDefense")
    POLICE_FIRE_CIVIL_DEFENSE("Police_Fire_CivilDefense"),
    @XmlEnumValue("Embassies_Chanceries")
    EMBASSIES_CHANCERIES("Embassies_Chanceries"),
    @XmlEnumValue("CorrectionalFacility")
    CORRECTIONAL_FACILITY("CorrectionalFacility"),
    @XmlEnumValue("CommunityCenter")
    COMMUNITY_CENTER("CommunityCenter"),
    @XmlEnumValue("HistoricalDistrict")
    HISTORICAL_DISTRICT("HistoricalDistrict"),
    @XmlEnumValue("FederalBuilding")
    FEDERAL_BUILDING("FederalBuilding"),
    @XmlEnumValue("IndianReservation")
    INDIAN_RESERVATION("IndianReservation"),
    @XmlEnumValue("Art")
    ART("Art"),
    @XmlEnumValue("MilitaryBuilding")
    MILITARY_BUILDING("MilitaryBuilding"),
    @XmlEnumValue("PossessoryInterest")
    POSSESSORY_INTEREST("PossessoryInterest"),
    @XmlEnumValue("NurserySchool")
    NURSERY_SCHOOL("NurserySchool"),
    @XmlEnumValue("HighSchool")
    HIGH_SCHOOL("HighSchool"),
    @XmlEnumValue("PrivateSchool")
    PRIVATE_SCHOOL("PrivateSchool"),
    @XmlEnumValue("Vocational_TradeSchool")
    VOCATIONAL_TRADE_SCHOOL("Vocational_TradeSchool"),
    @XmlEnumValue("EducationalService")
    EDUCATIONAL_SERVICE("EducationalService"),
    @XmlEnumValue("SecondaryEducationalSchool")
    SECONDARY_EDUCATIONAL_SCHOOL("SecondaryEducationalSchool"),
    @XmlEnumValue("PublicSchool")
    PUBLIC_SCHOOL("PublicSchool"),
    @XmlEnumValue("PublicService")
    PUBLIC_SERVICE("PublicService"),
    @XmlEnumValue("Charity")
    CHARITY("Charity"),
    @XmlEnumValue("Religious")
    RELIGIOUS("Religious");
    private final String value;

    PublicAndSemiPublicEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PublicAndSemiPublicEnum fromValue(String v) {
        for (PublicAndSemiPublicEnum c: PublicAndSemiPublicEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
