//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QUESTIONNAIRE_SECTION_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QUESTIONNAIRE_SECTION_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SectionLevelIdentfier" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SectionIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SectionDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SectionAdditionalDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SectionType" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SectionNote" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QUESTIONNAIRE_SECTION_DETAIL", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "sectionLevelIdentfier",
    "sectionIdentifier",
    "sectionDescription",
    "sectionAdditionalDescription",
    "sectionType",
    "sectionNote"
})
public class QUESTIONNAIRESECTIONDETAIL {

    @XmlElement(name = "SectionLevelIdentfier")
    protected MISMOString sectionLevelIdentfier;
    @XmlElement(name = "SectionIdentifier")
    protected MISMOString sectionIdentifier;
    @XmlElement(name = "SectionDescription")
    protected MISMOString sectionDescription;
    @XmlElement(name = "SectionAdditionalDescription")
    protected MISMOString sectionAdditionalDescription;
    @XmlElement(name = "SectionType")
    protected MISMOString sectionType;
    @XmlElement(name = "SectionNote")
    protected MISMOString sectionNote;

    /**
     * Gets the value of the sectionLevelIdentfier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSectionLevelIdentfier() {
        return sectionLevelIdentfier;
    }

    /**
     * Sets the value of the sectionLevelIdentfier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSectionLevelIdentfier(MISMOString value) {
        this.sectionLevelIdentfier = value;
    }

    /**
     * Gets the value of the sectionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSectionIdentifier() {
        return sectionIdentifier;
    }

    /**
     * Sets the value of the sectionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSectionIdentifier(MISMOString value) {
        this.sectionIdentifier = value;
    }

    /**
     * Gets the value of the sectionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSectionDescription() {
        return sectionDescription;
    }

    /**
     * Sets the value of the sectionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSectionDescription(MISMOString value) {
        this.sectionDescription = value;
    }

    /**
     * Gets the value of the sectionAdditionalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSectionAdditionalDescription() {
        return sectionAdditionalDescription;
    }

    /**
     * Sets the value of the sectionAdditionalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSectionAdditionalDescription(MISMOString value) {
        this.sectionAdditionalDescription = value;
    }

    /**
     * Gets the value of the sectionType property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSectionType() {
        return sectionType;
    }

    /**
     * Sets the value of the sectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSectionType(MISMOString value) {
        this.sectionType = value;
    }

    /**
     * Gets the value of the sectionNote property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSectionNote() {
        return sectionNote;
    }

    /**
     * Sets the value of the sectionNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSectionNote(MISMOString value) {
        this.sectionNote = value;
    }

}
