//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QUESTIONNAIRE_SUBSECTION_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QUESTIONNAIRE_SUBSECTION_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubSectionLevelIdentfier" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SubSectionIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SubSectionDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SubSectionAdditionalDescription" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SubSectionName" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *         &lt;element name="SubSectionNote" type="{http://www.mismo.org/residential/2009/schemas}MISMOString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QUESTIONNAIRE_SUBSECTION_DETAIL", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "subSectionLevelIdentfier",
    "subSectionIdentifier",
    "subSectionDescription",
    "subSectionAdditionalDescription",
    "subSectionName",
    "subSectionNote"
})
public class QUESTIONNAIRESUBSECTIONDETAIL {

    @XmlElement(name = "SubSectionLevelIdentfier")
    protected MISMOString subSectionLevelIdentfier;
    @XmlElement(name = "SubSectionIdentifier")
    protected MISMOString subSectionIdentifier;
    @XmlElement(name = "SubSectionDescription")
    protected MISMOString subSectionDescription;
    @XmlElement(name = "SubSectionAdditionalDescription")
    protected MISMOString subSectionAdditionalDescription;
    @XmlElement(name = "SubSectionName")
    protected MISMOString subSectionName;
    @XmlElement(name = "SubSectionNote")
    protected MISMOString subSectionNote;

    /**
     * Gets the value of the subSectionLevelIdentfier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSubSectionLevelIdentfier() {
        return subSectionLevelIdentfier;
    }

    /**
     * Sets the value of the subSectionLevelIdentfier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSubSectionLevelIdentfier(MISMOString value) {
        this.subSectionLevelIdentfier = value;
    }

    /**
     * Gets the value of the subSectionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSubSectionIdentifier() {
        return subSectionIdentifier;
    }

    /**
     * Sets the value of the subSectionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSubSectionIdentifier(MISMOString value) {
        this.subSectionIdentifier = value;
    }

    /**
     * Gets the value of the subSectionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSubSectionDescription() {
        return subSectionDescription;
    }

    /**
     * Sets the value of the subSectionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSubSectionDescription(MISMOString value) {
        this.subSectionDescription = value;
    }

    /**
     * Gets the value of the subSectionAdditionalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSubSectionAdditionalDescription() {
        return subSectionAdditionalDescription;
    }

    /**
     * Sets the value of the subSectionAdditionalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSubSectionAdditionalDescription(MISMOString value) {
        this.subSectionAdditionalDescription = value;
    }

    /**
     * Gets the value of the subSectionName property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSubSectionName() {
        return subSectionName;
    }

    /**
     * Sets the value of the subSectionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSubSectionName(MISMOString value) {
        this.subSectionName = value;
    }

    /**
     * Gets the value of the subSectionNote property.
     * 
     * @return
     *     possible object is
     *     {@link MISMOString }
     *     
     */
    public MISMOString getSubSectionNote() {
        return subSectionNote;
    }

    /**
     * Sets the value of the subSectionNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISMOString }
     *     
     */
    public void setSubSectionNote(MISMOString value) {
        this.subSectionNote = value;
    }

}
