//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about the parcel tax line bill. 
 * 
 * <p>Java class for TAX_BILL_CORELOGIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAX_BILL_CORELOGIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TAX_BILL_DETAIL" type="{http://globalgateway.corelogic.com/order/2015}TAX_BILL_DETAIL_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="TAX_INSTALLMENTS" type="{http://globalgateway.corelogic.com/order/2015}TAX_INSTALLMENTS_CORELOGIC" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAX_BILL_CORELOGIC", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "taxbilldetail",
    "taxinstallments"
})
public class TAXBILLCORELOGIC {

    @XmlElement(name = "TAX_BILL_DETAIL")
    protected TAXBILLDETAILCORELOGIC taxbilldetail;
    @XmlElement(name = "TAX_INSTALLMENTS")
    protected TAXINSTALLMENTSCORELOGIC taxinstallments;

    /**
     * Gets the value of the taxbilldetail property.
     * 
     * @return
     *     possible object is
     *     {@link TAXBILLDETAILCORELOGIC }
     *     
     */
    public TAXBILLDETAILCORELOGIC getTAXBILLDETAIL() {
        return taxbilldetail;
    }

    /**
     * Sets the value of the taxbilldetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAXBILLDETAILCORELOGIC }
     *     
     */
    public void setTAXBILLDETAIL(TAXBILLDETAILCORELOGIC value) {
        this.taxbilldetail = value;
    }

    /**
     * Gets the value of the taxinstallments property.
     * 
     * @return
     *     possible object is
     *     {@link TAXINSTALLMENTSCORELOGIC }
     *     
     */
    public TAXINSTALLMENTSCORELOGIC getTAXINSTALLMENTS() {
        return taxinstallments;
    }

    /**
     * Sets the value of the taxinstallments property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAXINSTALLMENTSCORELOGIC }
     *     
     */
    public void setTAXINSTALLMENTS(TAXINSTALLMENTSCORELOGIC value) {
        this.taxinstallments = value;
    }

}
