//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about the parcel tax line. 
 * 
 * <p>Java class for TAX_LINE_CORELOGIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAX_LINE_CORELOGIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PAYEE" type="{http://globalgateway.corelogic.com/order/2015}PAYEE_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="TAX_BILLS" type="{http://globalgateway.corelogic.com/order/2015}TAX_BILLS_CORELOGIC" minOccurs="0"/>
 *         &lt;element name="TAX_LINE_DETAIL" type="{http://globalgateway.corelogic.com/order/2015}TAX_LINE_DETAIL_CORELOGIC" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAX_LINE_CORELOGIC", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "payee",
    "taxbills",
    "taxlinedetail"
})
public class TAXLINECORELOGIC {

    @XmlElement(name = "PAYEE")
    protected PAYEECORELOGIC payee;
    @XmlElement(name = "TAX_BILLS")
    protected TAXBILLSCORELOGIC taxbills;
    @XmlElement(name = "TAX_LINE_DETAIL")
    protected TAXLINEDETAILCORELOGIC taxlinedetail;

    /**
     * Gets the value of the payee property.
     * 
     * @return
     *     possible object is
     *     {@link PAYEECORELOGIC }
     *     
     */
    public PAYEECORELOGIC getPAYEE() {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     * 
     * @param value
     *     allowed object is
     *     {@link PAYEECORELOGIC }
     *     
     */
    public void setPAYEE(PAYEECORELOGIC value) {
        this.payee = value;
    }

    /**
     * Gets the value of the taxbills property.
     * 
     * @return
     *     possible object is
     *     {@link TAXBILLSCORELOGIC }
     *     
     */
    public TAXBILLSCORELOGIC getTAXBILLS() {
        return taxbills;
    }

    /**
     * Sets the value of the taxbills property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAXBILLSCORELOGIC }
     *     
     */
    public void setTAXBILLS(TAXBILLSCORELOGIC value) {
        this.taxbills = value;
    }

    /**
     * Gets the value of the taxlinedetail property.
     * 
     * @return
     *     possible object is
     *     {@link TAXLINEDETAILCORELOGIC }
     *     
     */
    public TAXLINEDETAILCORELOGIC getTAXLINEDETAIL() {
        return taxlinedetail;
    }

    /**
     * Sets the value of the taxlinedetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAXLINEDETAILCORELOGIC }
     *     
     */
    public void setTAXLINEDETAIL(TAXLINEDETAILCORELOGIC value) {
        this.taxlinedetail = value;
    }

}
