//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TAX_REQUEST_DETAIL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAX_REQUEST_DETAIL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxRequestActionType" type="{http://globalgateway.corelogic.com/order/2015}TaxRequestActionEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAX_REQUEST_DETAIL", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "taxRequestActionType"
})
public class TAXREQUESTDETAIL {

    @XmlElement(name = "TaxRequestActionType")
    protected TaxRequestActionEnum taxRequestActionType;

    /**
     * Gets the value of the taxRequestActionType property.
     * 
     * @return
     *     possible object is
     *     {@link TaxRequestActionEnum }
     *     
     */
    public TaxRequestActionEnum getTaxRequestActionType() {
        return taxRequestActionType;
    }

    /**
     * Sets the value of the taxRequestActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxRequestActionEnum }
     *     
     */
    public void setTaxRequestActionType(TaxRequestActionEnum value) {
        this.taxRequestActionType = value;
    }

}
