//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 04:46:29 AM CAT 
//


package qubed.corelogic;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VERIFICATION_OF_INCOME_RESPONSE_PRICES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VERIFICATION_OF_INCOME_RESPONSE_PRICES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VERIFICATION_OF_INCOME_RESPONSE_PRICE" type="{http://globalgateway.corelogic.com/order/2015}VERIFICATION_OF_INCOME_RESPONSE_PRICE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VERIFICATION_OF_INCOME_RESPONSE_PRICES", namespace = "http://globalgateway.corelogic.com/order/2015", propOrder = {
    "verificationofincomeresponseprice"
})
public class VERIFICATIONOFINCOMERESPONSEPRICES {

    @XmlElement(name = "VERIFICATION_OF_INCOME_RESPONSE_PRICE")
    protected List<VERIFICATIONOFINCOMERESPONSEPRICE> verificationofincomeresponseprice;

    /**
     * Gets the value of the verificationofincomeresponseprice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the verificationofincomeresponseprice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVERIFICATIONOFINCOMERESPONSEPRICE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VERIFICATIONOFINCOMERESPONSEPRICE }
     * 
     * 
     */
    public List<VERIFICATIONOFINCOMERESPONSEPRICE> getVERIFICATIONOFINCOMERESPONSEPRICE() {
        if (verificationofincomeresponseprice == null) {
            verificationofincomeresponseprice = new ArrayList<VERIFICATIONOFINCOMERESPONSEPRICE>();
        }
        return this.verificationofincomeresponseprice;
    }

}
